/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, copyDefault, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && (copyDefault || key !== "default"))
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toCommonJS = /* @__PURE__ */ ((cache) => {
  return (module2, temp) => {
    return cache && cache.get(module2) || (temp = __reExport(__markAsModule({}), module2, 1), cache && cache.set(module2, temp), temp);
  };
})(typeof WeakMap !== "undefined" ? /* @__PURE__ */ new WeakMap() : 0);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_VIEWDAY: () => VIEW_TYPE_VIEWDAY,
  default: () => ViewdayPlugin
});
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  viewId: "",
  meetingNoteFolder: "Meeting Notes",
  localRules: []
};
var VIEW_TYPE_VIEWDAY = "viewday-google-calendar";
var ViewdayPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
  }
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addSettingTab(new ViewdaySettingTab(this.app, this));
      this.registerView(VIEW_TYPE_VIEWDAY, (leaf) => this.view = new ViewdayView(leaf, this.settings, this));
      this.addRibbonIcon("calendar-days", "Open Viewday", () => {
        void this.activateView();
      });
      this.registerDomEvent(window, "message", (event) => {
        void this.handleMessage(event);
      });
      const requestSync = (0, import_obsidian.debounce)(() => {
        void this.pushLocalEvents();
        void this.pushLinkedNotes();
      }, 1e3, true);
      this.registerEvent(this.app.metadataCache.on("changed", (file) => {
        requestSync();
      }));
      this.registerEvent(this.app.vault.on("rename", requestSync));
      this.registerEvent(this.app.vault.on("delete", requestSync));
    });
  }
  scanForUnscheduled(activeRules) {
    return __async(this, null, function* () {
      var _a, _b;
      if (!this.view || !activeRules || !activeRules.length) {
        (_a = this.view) == null ? void 0 : _a.postMessage({ type: "UNSCHEDULED_RESULTS", items: [] });
        return;
      }
      const items = [];
      const files = this.app.vault.getMarkdownFiles();
      for (const rule of activeRules) {
        const ruleFolder = rule.folder_path || rule.path || rule.folder || "";
        for (const file of files) {
          if (ruleFolder && !file.path.startsWith(ruleFolder))
            continue;
          const cache = this.app.metadataCache.getFileCache(file);
          const frontmatter = (cache == null ? void 0 : cache.frontmatter) || {};
          const property = rule.property;
          const val = frontmatter[property];
          let isUnscheduled = false;
          if (!ruleFolder) {
            if (val !== void 0 && (val === null || val === "")) {
              isUnscheduled = true;
            }
          } else {
            if (val === void 0 || val === null || val === "") {
              isUnscheduled = true;
            }
          }
          if (isUnscheduled) {
            let durationVal = frontmatter["duration_minutes"];
            if (!durationVal)
              durationVal = frontmatter["duration"];
            const finalDuration = durationVal ? Number(durationVal) : void 0;
            items.push({
              path: file.path,
              basename: file.basename,
              folder: ((_b = file.parent) == null ? void 0 : _b.path) || "",
              sourceId: rule.id,
              property: rule.property,
              sourceColor: rule.color,
              duration: finalDuration
            });
          }
        }
      }
      const uniqueItems = Array.from(new Map(items.map((item) => [item.path, item])).values());
      this.view.postMessage({
        type: "UNSCHEDULED_RESULTS",
        items: uniqueItems
      });
    });
  }
  pushLocalEvents() {
    return __async(this, null, function* () {
      if (!this.view || !this.settings.localRules.length)
        return;
      const events = [];
      const files = this.app.vault.getMarkdownFiles();
      for (const file of files) {
        const cache = this.app.metadataCache.getFileCache(file);
        if (!(cache == null ? void 0 : cache.frontmatter))
          continue;
        for (const rule of this.settings.localRules) {
          if (!rule.active)
            continue;
          const ruleFolder = rule.folder_path || rule.path || rule.folder || "";
          if (ruleFolder && !file.path.startsWith(ruleFolder))
            continue;
          const dateVal = cache.frontmatter[rule.property];
          let durationVal = cache.frontmatter["duration_minutes"];
          if (!durationVal)
            durationVal = cache.frontmatter["duration"];
          if (dateVal) {
            const isAllDay = typeof dateVal === "string" && !dateVal.includes("T");
            let endVal = void 0;
            if (!isAllDay && durationVal) {
              const startMs = Date.parse(dateVal);
              const durMin = Number(durationVal);
              if (!isNaN(startMs) && !isNaN(durMin) && durMin > 0) {
                const addMinutesToIso = (iso, minutes) => {
                  const [d, t] = iso.split("T");
                  if (!d || !t)
                    return void 0;
                  const [y, m, day] = d.split("-").map(Number);
                  const [hr, min] = t.split(":").map(Number);
                  const date = new Date(y, m - 1, day, hr, min + minutes);
                  const ny = date.getFullYear();
                  const nm = String(date.getMonth() + 1).padStart(2, "0");
                  const nd = String(date.getDate()).padStart(2, "0");
                  const nh = String(date.getHours()).padStart(2, "0");
                  const nmn = String(date.getMinutes()).padStart(2, "0");
                  return `${ny}-${nm}-${nd}T${nh}:${nmn}`;
                };
                endVal = addMinutesToIso(dateVal, durMin);
              }
            }
            events.push({
              id: `local::${file.path}::${rule.id}`,
              title: file.basename,
              start: dateVal,
              end: endVal,
              allDay: isAllDay,
              backgroundColor: rule.color,
              borderColor: rule.color,
              extendedProps: {
                type: "local",
                path: file.path,
                ruleId: rule.id,
                property: rule.property
              }
            });
          }
        }
      }
      this.view.postMessage({
        type: "SYNC_LOCAL_EVENTS",
        events,
        sources: this.settings.localRules
      });
    });
  }
  pushLinkedNotes() {
    return __async(this, null, function* () {
      var _a, _b;
      if (!this.view)
        return;
      const linkedNotes = {};
      const files = this.app.vault.getMarkdownFiles();
      for (const file of files) {
        const cache = this.app.metadataCache.getFileCache(file);
        const links = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a["viewday_links"];
        if (links !== void 0 && links !== null) {
          let eventIds = [];
          if (Array.isArray(links)) {
            eventIds = links.map(String);
          } else {
            eventIds = [String(links)];
          }
          for (const id of eventIds) {
            let targetIds = [id];
            if (id.startsWith("[[") && id.endsWith("]]")) {
              const linkText = id.substring(2, id.length - 2);
              const targetFile = this.app.metadataCache.getFirstLinkpathDest(linkText, "");
              if (targetFile instanceof import_obsidian.TFile) {
                targetIds = [];
                for (const rule of this.settings.localRules) {
                  if (!rule.active)
                    continue;
                  const ruleFolder = rule.folder_path || rule.path || rule.folder || "";
                  if (ruleFolder && !targetFile.path.startsWith(ruleFolder))
                    continue;
                  const targetCache = this.app.metadataCache.getFileCache(targetFile);
                  if ((_b = targetCache == null ? void 0 : targetCache.frontmatter) == null ? void 0 : _b[rule.property]) {
                    targetIds.push(`local::${targetFile.path}::${rule.id}`);
                  }
                }
              }
            }
            for (const tid of targetIds) {
              if (!linkedNotes[tid]) {
                linkedNotes[tid] = [];
              }
              linkedNotes[tid].push({
                path: file.path,
                basename: file.basename
              });
            }
          }
        }
      }
      this.view.postMessage({
        type: "SYNC_LINKED_NOTES",
        linkedNotes
      });
    });
  }
  handleMessage(event) {
    return __async(this, null, function* () {
      if (event.origin !== "https://viewday.app" && event.origin !== "http://localhost:3000")
        return;
      const { type, eventData, localPath, payload, rules, sources } = event.data;
      if (type === "FETCH_UNSCHEDULED" && sources) {
        yield this.scanForUnscheduled(sources);
      }
      if (type === "CONFIGURE_RULES" && rules) {
        this.settings.localRules = rules;
        yield this.saveData(this.settings);
        yield this.pushLocalEvents();
        yield this.pushLinkedNotes();
      }
      if (type === "UPDATE_LOCAL_EVENT" && payload) {
        yield this.updateLocalEvent(payload);
      }
      if (type === "UPDATE_NOTE_DATE" && payload) {
        yield this.updateLocalEvent(payload);
      }
      if (type === "create-meeting-note" && eventData) {
        yield this.createMeetingNote(eventData);
      }
      if (type === "open-local-file" && localPath) {
        const file = this.app.vault.getAbstractFileByPath(localPath);
        if (file instanceof import_obsidian.TFile) {
          const leaf = this.app.workspace.getLeaf(false);
          yield leaf.openFile(file);
        } else {
          new import_obsidian.Notice(`Could not find file: ${localPath}`);
        }
      }
      if (type === "TRIGGER_FUZZY_SEARCH" && event.data.eventId) {
        new LinkedNoteSuggester(this.app, this, event.data.eventId).open();
      }
      if (type === "UNLINK_DOCUMENT" && event.data.eventId && event.data.path) {
        yield this.unlinkDocument(event.data.path, event.data.eventId);
      }
      if (type === "viewday-ready") {
        yield this.pushLocalEvents();
        yield this.pushLinkedNotes();
      }
      if (type === "OPEN_EXTERNAL_URL" && event.data.url) {
        window.open(event.data.url);
      }
      if (type === "CREATE_LOCAL_NOTE" && payload) {
        yield this.createLocalNote(payload);
      }
      if (type === "OPEN_PERIODIC_NOTE" && event.data.period && event.data.date) {
        yield this.openPeriodicNote(event.data.period, event.data.date);
      }
    });
  }
  openPeriodicNote(period, date) {
    return __async(this, null, function* () {
      var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k;
      try {
        let folder = "";
        let format = "";
        if (period === "daily") {
          const periodicNotes = (_a = this.app.plugins) == null ? void 0 : _a.getPlugin("periodic-notes");
          if ((_c = (_b = periodicNotes == null ? void 0 : periodicNotes.settings) == null ? void 0 : _b.daily) == null ? void 0 : _c.enabled) {
            folder = periodicNotes.settings.daily.folder || "";
            format = periodicNotes.settings.daily.format || "YYYY-MM-DD";
          } else {
            const dailyNotes = (_d = this.app.internalPlugins) == null ? void 0 : _d.getPluginById("daily-notes");
            folder = ((_f = (_e = dailyNotes == null ? void 0 : dailyNotes.instance) == null ? void 0 : _e.options) == null ? void 0 : _f.folder) || "";
            format = ((_h = (_g = dailyNotes == null ? void 0 : dailyNotes.instance) == null ? void 0 : _g.options) == null ? void 0 : _h.format) || "YYYY-MM-DD";
          }
          if (!format)
            format = "YYYY-MM-DD";
          const moment = window.moment;
          if (!moment) {
            new import_obsidian.Notice("Viewday: moment.js not available.");
            return;
          }
          const noteName = moment(date, "YYYY-MM-DD").format(format);
          const fileName = `${noteName}.md`;
          const filePath = folder ? `${folder}/${fileName}` : fileName;
          let file = this.app.vault.getAbstractFileByPath(filePath);
          if (!file) {
            file = this.app.metadataCache.getFirstLinkpathDest(noteName, "") || null;
          }
          if (file instanceof import_obsidian.TFile) {
            const leaf = this.app.workspace.getLeaf(false);
            yield leaf.openFile(file);
          } else {
            if (folder && !this.app.vault.getAbstractFileByPath(folder)) {
              yield this.app.vault.createFolder(folder);
            }
            const newFile = yield this.app.vault.create(filePath, "");
            const leaf = this.app.workspace.getLeaf(false);
            yield leaf.openFile(newFile);
            new import_obsidian.Notice(`Created daily note: ${fileName}`);
          }
        } else if (period === "weekly") {
          const periodicNotes = (_i = this.app.plugins) == null ? void 0 : _i.getPlugin("periodic-notes");
          if ((_k = (_j = periodicNotes == null ? void 0 : periodicNotes.settings) == null ? void 0 : _j.weekly) == null ? void 0 : _k.enabled) {
            folder = periodicNotes.settings.weekly.folder || "";
            format = periodicNotes.settings.weekly.format || "gggg-[W]WW";
          } else {
            folder = "";
            format = "gggg-[W]WW";
          }
          if (!format)
            format = "gggg-[W]WW";
          const moment = window.moment;
          if (!moment) {
            new import_obsidian.Notice("Viewday: moment.js not available.");
            return;
          }
          const [yearStr, weekStr] = date.split("-W");
          const weekMoment = moment().isoWeekYear(parseInt(yearStr)).isoWeek(parseInt(weekStr)).startOf("isoWeek");
          const noteName = weekMoment.format(format);
          const fileName = `${noteName}.md`;
          const filePath = folder ? `${folder}/${fileName}` : fileName;
          let file = this.app.vault.getAbstractFileByPath(filePath);
          if (!file) {
            file = this.app.metadataCache.getFirstLinkpathDest(noteName, "") || null;
          }
          if (file instanceof import_obsidian.TFile) {
            const leaf = this.app.workspace.getLeaf(false);
            yield leaf.openFile(file);
          } else {
            if (folder && !this.app.vault.getAbstractFileByPath(folder)) {
              yield this.app.vault.createFolder(folder);
            }
            const newFile = yield this.app.vault.create(filePath, "");
            const leaf = this.app.workspace.getLeaf(false);
            yield leaf.openFile(newFile);
            new import_obsidian.Notice(`Created weekly note: ${fileName}`);
          }
        }
      } catch (err) {
        console.error("Viewday: Failed to open periodic note", err);
        new import_obsidian.Notice("Viewday: Could not open periodic note. Make sure the Daily Notes or Periodic Notes plugin is enabled.");
      }
    });
  }
  createLocalNote(payload) {
    return __async(this, null, function* () {
      const { title, frontmatter, folder } = payload;
      const safeTitle = (title || "Untitled").replace(/[\\/:*?"<>|]/g, "");
      let fileName = `${safeTitle}.md`;
      let folderPath = folder || "";
      let filePath = folderPath ? `${folderPath}/${fileName}` : fileName;
      try {
        if (folderPath && !this.app.vault.getAbstractFileByPath(folderPath)) {
          yield this.app.vault.createFolder(folderPath);
        }
        let fileExists = this.app.vault.getAbstractFileByPath(filePath);
        let i = 1;
        while (fileExists) {
          fileName = `${safeTitle} (${i}).md`;
          filePath = folderPath ? `${folderPath}/${fileName}` : fileName;
          fileExists = this.app.vault.getAbstractFileByPath(filePath);
          i++;
        }
        const yamlLines = ["---"];
        if (frontmatter) {
          for (const [key, value] of Object.entries(frontmatter)) {
            if (value !== void 0 && value !== null) {
              yamlLines.push(`${key}: ${value}`);
            }
          }
        }
        yamlLines.push("---");
        yamlLines.push("");
        yamlLines.push(`# ${title}`);
        yamlLines.push("");
        const fileContent = yamlLines.join("\n");
        const newFile = yield this.app.vault.create(filePath, fileContent);
        const leaf = this.app.workspace.getLeaf(false);
        yield leaf.openFile(newFile);
        new import_obsidian.Notice(`Created: ${fileName}`);
      } catch (error) {
        console.error("Viewday: Failed to create local note", error);
        new import_obsidian.Notice("Viewday: Failed to create note.");
      }
    });
  }
  updateLocalEvent(payload) {
    return __async(this, null, function* () {
      const { path, property, newValue, duration } = payload;
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile) {
        try {
          yield this.app.fileManager.processFrontMatter(file, (frontmatter) => {
            if (newValue === null) {
              frontmatter[property] = null;
            } else {
              frontmatter[property] = newValue;
              if (duration !== void 0 && duration !== null) {
                frontmatter["duration_minutes"] = duration;
              }
            }
          });
          new import_obsidian.Notice(`Rescheduled: ${file.basename}`);
        } catch (err) {
          console.error("Viewday: Failed to update file", err);
          new import_obsidian.Notice("Viewday: Failed to update event date.");
        }
      }
    });
  }
  unlinkDocument(path, eventId) {
    return __async(this, null, function* () {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian.TFile) {
        try {
          yield this.app.fileManager.processFrontMatter(file, (frontmatter) => {
            let links = frontmatter["viewday_links"];
            if (Array.isArray(links)) {
              frontmatter["viewday_links"] = links.filter((id) => id !== eventId);
            } else if (links !== void 0 && String(links) === eventId) {
              frontmatter["viewday_links"] = [];
            }
          });
          new import_obsidian.Notice(`Unlinked note from event`);
        } catch (err) {
          console.error("Viewday: Failed to unlink note", err);
          new import_obsidian.Notice("Viewday: Failed to unlink note.");
        }
      }
    });
  }
  createMeetingNote(data) {
    return __async(this, null, function* () {
      const escapeYaml = (text) => (text || "").replace(/"/g, '\\"');
      const { title, date, time, location, meetingLink, organizer, attendees, description, attachments, gcalLink } = data;
      const safeTitle = (title || "Untitled Event").replace(/[\\/:*?"<>|]/g, "");
      const fileName = `${date} - ${safeTitle}.md`;
      const folderPath = this.settings.meetingNoteFolder;
      const filePath = `${folderPath}/${fileName}`;
      try {
        if (!this.app.vault.getAbstractFileByPath(folderPath)) {
          yield this.app.vault.createFolder(folderPath);
        }
        const existingFile = this.app.vault.getAbstractFileByPath(filePath);
        if (existingFile instanceof import_obsidian.TFile) {
          const leaf2 = this.app.workspace.getLeaf(false);
          yield leaf2.openFile(existingFile);
          new import_obsidian.Notice(`Opened existing note: ${fileName}`);
          return;
        }
        let fileContent = `---
date: ${date}
time: ${time}
location: "${escapeYaml(location)}"
organizer: "${escapeYaml(organizer)}"
meeting_link: "${meetingLink || ""}"
google_cal_link: "${gcalLink || ""}"
attendees: [${attendees ? attendees.map((a) => `"${escapeYaml(a)}"`).join(", ") : ""}]
tags: [meeting]
---
# ${title}

`;
        if (meetingLink)
          fileContent += `[Join Meeting](${meetingLink})

`;
        fileContent += `## Agenda
${description || "No agenda provided."}

`;
        if (attachments && attachments.length > 0) {
          fileContent += `## Attachments
`;
          attachments.forEach((att) => {
            if (att.url)
              fileContent += `- [${att.title}](${att.url})
`;
          });
          fileContent += `
`;
        }
        fileContent += `## Notes
- 
`;
        const newFile = yield this.app.vault.create(filePath, fileContent);
        const leaf = this.app.workspace.getLeaf(false);
        yield leaf.openFile(newFile);
        new import_obsidian.Notice(`Created meeting note: ${fileName}`);
      } catch (error) {
        console.error("Viewday: Failed to create note", error);
        new import_obsidian.Notice("Viewday: Failed to create meeting note.");
      }
    });
  }
  activateView() {
    return __async(this, null, function* () {
      const { workspace } = this.app;
      let leaf = workspace.getLeavesOfType(VIEW_TYPE_VIEWDAY)[0];
      if (!leaf) {
        leaf = workspace.getRightLeaf(false);
        yield leaf.setViewState({ type: VIEW_TYPE_VIEWDAY, active: true });
      }
      void workspace.revealLeaf(leaf);
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
      yield this.pushLocalEvents();
      yield this.pushLinkedNotes();
      this.app.workspace.getLeavesOfType(VIEW_TYPE_VIEWDAY).forEach((leaf) => {
        if (leaf.view instanceof ViewdayView) {
          void leaf.view.onOpen();
        }
      });
    });
  }
};
var ViewdayView = class extends import_obsidian.ItemView {
  constructor(leaf, settings, plugin) {
    super(leaf);
    this.icon = "calendar-days";
    this.frame = null;
    this.settings = settings;
    this.plugin = plugin;
    this.registerEvent(this.app.workspace.on("css-change", () => {
      void this.onOpen();
    }));
  }
  getViewType() {
    return VIEW_TYPE_VIEWDAY;
  }
  getDisplayText() {
    return "Viewday calendar";
  }
  postMessage(msg) {
    if (this.frame && this.frame.contentWindow) {
      this.frame.contentWindow.postMessage(msg, "*");
    }
  }
  onOpen() {
    return __async(this, null, function* () {
      yield Promise.resolve();
      const container = this.contentEl;
      container.empty();
      if (!this.settings.viewId) {
        container.createEl("h4", { text: 'Please set your "View Id" in settings.' });
        return;
      }
      const isDark = document.body.classList.contains("theme-dark");
      this.frame = container.createEl("iframe", {
        cls: "viewday-iframe",
        attr: {
          src: `https://viewday.app/embed/${this.settings.viewId}?platform=obsidian&theme=${isDark ? "dark" : "light"}`,
          sandbox: "allow-scripts allow-same-origin allow-popups"
        }
      });
    });
  }
};
var ViewdaySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const headerSetting = new import_obsidian.Setting(containerEl).setName("Google Calendar by Viewday").setDesc("A real-time Google Calendar for Obsidian with multi-account sync.");
    headerSetting.nameEl.addClass("viewday-settings-header-name");
    new import_obsidian.Setting(containerEl).setName("View Id").setDesc('Enter the "View Id" from your Viewday dashboard.').addText((text) => text.setPlaceholder("Paste Id here...").setValue(this.plugin.settings.viewId).onChange((value) => {
      this.plugin.settings.viewId = value;
      void this.plugin.saveSettings().then(() => {
        refreshSuccessMessage(value);
      });
    }));
    new import_obsidian.Setting(containerEl).setName("Meeting notes folder").setDesc("Where should new meeting notes be created?").addText((text) => text.setPlaceholder("Meeting Notes").setValue(this.plugin.settings.meetingNoteFolder).onChange((value) => {
      this.plugin.settings.meetingNoteFolder = value;
      void this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Local Sources", cls: "viewday-section-header" });
    const desc = containerEl.createDiv({ cls: "viewday-section-desc" });
    desc.createSpan({ text: "Visualize tasks and notes from your vault on the calendar. " });
    desc.createSpan({ text: "Configuration is managed in your " });
    desc.createEl("a", { text: "Viewday Dashboard", href: "https://viewday.app/dashboard?tab=sources" });
    desc.createSpan({ text: "." });
    if (this.plugin.settings.localRules.length > 0) {
      const list = containerEl.createDiv({ cls: "viewday-rules-list" });
      list.createDiv({ text: "Active Rules:", cls: "viewday-active-rules-header" });
      this.plugin.settings.localRules.forEach((rule) => {
        const item = list.createDiv({ cls: "viewday-rule-item" });
        const dot = item.createSpan({ cls: "viewday-rule-dot" });
        dot.style.backgroundColor = rule.color;
        const text = item.createSpan({ cls: "viewday-rule-text" });
        const folderDisplayName = rule.folder_path || rule.path || rule.folder || "/";
        text.innerText = `${rule.name} (property: ${rule.property} \u2022 folder: ${folderDisplayName})`;
      });
    } else {
      containerEl.createDiv({
        cls: "viewday-empty-rules",
        text: "No local rules configured yet."
      });
    }
    const successContainer = containerEl.createDiv();
    const refreshSuccessMessage = (id) => {
      successContainer.empty();
      if (id && id.length > 0) {
        successContainer.addClass("viewday-success-container");
        successContainer.createSpan({ text: "All set! Click the calendar icon" });
        const iconSpan = successContainer.createSpan();
        (0, import_obsidian.setIcon)(iconSpan, "calendar-days");
        successContainer.createSpan({ text: "in your sidebar to view your schedule." });
      }
    };
    refreshSuccessMessage(this.plugin.settings.viewId);
    const linkContainer = containerEl.createDiv({ cls: "viewday-link-container" });
    const createLink = (text, href) => {
      linkContainer.createEl("a", { text, href, cls: "viewday-footer-link" });
    };
    createLink("Go to Viewday dashboard \u2197", "https://viewday.app/dashboard");
    createLink("Request a feature \u2197", "https://viewday.app/feature-requests");
    createLink("Need help? Contact us \u2197", "https://viewday.app/contact");
  }
};
var LinkedNoteSuggester = class extends import_obsidian.FuzzySuggestModal {
  constructor(app, plugin, eventId) {
    super(app);
    this.plugin = plugin;
    this.eventId = eventId;
    this.setPlaceholder("Search for a note to link...");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file, evt) {
    return __async(this, null, function* () {
      try {
        let finalId = this.eventId;
        if (finalId.startsWith("local::")) {
          const parts = finalId.split("::");
          if (parts.length >= 2) {
            const filePath = parts[1];
            const targetFile = this.plugin.app.vault.getAbstractFileByPath(filePath);
            if (targetFile instanceof import_obsidian.TFile) {
              finalId = `[[${targetFile.basename}]]`;
            }
          }
        }
        yield this.app.fileManager.processFrontMatter(file, (frontmatter) => {
          let links = frontmatter["viewday_links"];
          if (!links) {
            frontmatter["viewday_links"] = [finalId];
          } else if (Array.isArray(links)) {
            if (!links.includes(finalId)) {
              links.push(finalId);
            }
          } else {
            if (String(links) !== finalId) {
              frontmatter["viewday_links"] = [String(links), finalId];
            }
          }
        });
        new import_obsidian.Notice(`Linked: ${file.basename}`);
      } catch (err) {
        console.error("Viewday: Failed to link note", err);
        new import_obsidian.Notice("Viewday: Failed to link note.");
      }
    });
  }
};
module.exports = __toCommonJS(main_exports);
