/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MilestoneTimelinePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/constants.ts
var DEFAULT_SETTINGS = {
  dateFormat: "YYYY-MM-DD",
  sortOrder: "asc",
  showFileLinks: true,
  monthThreshold: 10,
  excludeScreenshots: true,
  includeTagDates: true,
  dateFormatPreference: "US",
  language: "en",
  includeYearOnly: true,
  showYearMarkersWithYearOnly: true
};
var LOCALIZATIONS = {
  "en": {
    monthNames: {
      full: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
      short: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
    },
    monthPatterns: {
      any: "January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec"
    },
    monthNameMap: {
      "january": 0,
      "jan": 0,
      "february": 1,
      "feb": 1,
      "march": 2,
      "mar": 2,
      "april": 3,
      "apr": 3,
      "may": 4,
      "june": 5,
      "jun": 5,
      "july": 6,
      "jul": 6,
      "august": 7,
      "aug": 7,
      "september": 8,
      "sep": 8,
      "october": 9,
      "oct": 9,
      "november": 10,
      "nov": 10,
      "december": 11,
      "dec": 11
    },
    ordinalSuffixes: {
      pattern: "st|nd|rd|th",
      examples: ["1st", "2nd", "3rd", "4th", "21st", "22nd", "23rd"]
    },
    dateFormatNotes: 'English uses ordinal suffixes (1st, 2nd, 3rd, etc.) and typically formats dates as "Month Day, Year" or "Day Month Year"'
  },
  "es": {
    monthNames: {
      full: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
      short: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"]
    },
    monthPatterns: {
      any: "Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre|Ene|Feb|Mar|Abr|May|Jun|Jul|Ago|Sep|Oct|Nov|Dic"
    },
    monthNameMap: {
      "enero": 0,
      "ene": 0,
      "febrero": 1,
      "feb": 1,
      "marzo": 2,
      "mar": 2,
      "abril": 3,
      "abr": 3,
      "mayo": 4,
      "may": 4,
      "junio": 5,
      "jun": 5,
      "julio": 6,
      "jul": 6,
      "agosto": 7,
      "ago": 7,
      "septiembre": 8,
      "sep": 8,
      "octubre": 9,
      "oct": 9,
      "noviembre": 10,
      "nov": 10,
      "diciembre": 11,
      "dic": 11
    },
    ordinalSuffixes: {
      pattern: "\xBA|\xAA|\xB0",
      examples: ["1\xBA", "2\xBA", "3\xBA", "1\xAA", "2\xAA", "3\xAA"]
    },
    dateFormatNotes: 'Spanish may use ordinal indicators (1\xBA, 2\xBA, 3\xBA) but typically writes dates without them: "15 de Mayo de 2024"'
  },
  "fr": {
    monthNames: {
      full: ["Janvier", "F\xE9vrier", "Mars", "Avril", "Mai", "Juin", "Juillet", "Ao\xFBt", "Septembre", "Octobre", "Novembre", "D\xE9cembre"],
      short: ["Jan", "F\xE9v", "Mar", "Avr", "Mai", "Jun", "Jul", "Ao\xFB", "Sep", "Oct", "Nov", "D\xE9c"]
    },
    monthPatterns: {
      any: "Janvier|F\xE9vrier|Mars|Avril|Mai|Juin|Juillet|Ao\xFBt|Septembre|Octobre|Novembre|D\xE9cembre|Jan|F\xE9v|Mar|Avr|Mai|Jun|Jul|Ao\xFB|Sep|Oct|Nov|D\xE9c"
    },
    monthNameMap: {
      "janvier": 0,
      "jan": 0,
      "f\xE9vrier": 1,
      "f\xE9v": 1,
      "mars": 2,
      "mar": 2,
      "avril": 3,
      "avr": 3,
      "mai": 4,
      "juin": 5,
      "jun": 5,
      "juillet": 6,
      "jul": 6,
      "ao\xFBt": 7,
      "ao\xFB": 7,
      "septembre": 8,
      "sep": 8,
      "octobre": 9,
      "oct": 9,
      "novembre": 10,
      "nov": 10,
      "d\xE9cembre": 11,
      "d\xE9c": 11
    },
    ordinalSuffixes: {
      pattern: "er|\xE8re|e|\xE8me|eme",
      examples: ["1er", "1\xE8re", "2e", "2\xE8me", "3e"]
    },
    dateFormatNotes: 'French uses ordinals primarily for "premier" (1er/1\xE8re) and abbreviated forms (2e, 3e): "1er Mai 2024" or "15 Mai 2024"'
  },
  "ja": {
    monthNames: {
      full: ["1\u6708", "2\u6708", "3\u6708", "4\u6708", "5\u6708", "6\u6708", "7\u6708", "8\u6708", "9\u6708", "10\u6708", "11\u6708", "12\u6708"],
      short: ["1\u6708", "2\u6708", "3\u6708", "4\u6708", "5\u6708", "6\u6708", "7\u6708", "8\u6708", "9\u6708", "10\u6708", "11\u6708", "12\u6708"]
    },
    monthPatterns: {
      any: "1\u6708|2\u6708|3\u6708|4\u6708|5\u6708|6\u6708|7\u6708|8\u6708|9\u6708|10\u6708|11\u6708|12\u6708"
    },
    monthNameMap: {
      "1\u6708": 0,
      "2\u6708": 1,
      "3\u6708": 2,
      "4\u6708": 3,
      "5\u6708": 4,
      "6\u6708": 5,
      "7\u6708": 6,
      "8\u6708": 7,
      "9\u6708": 8,
      "10\u6708": 9,
      "11\u6708": 10,
      "12\u6708": 11
    },
    ordinalSuffixes: {
      pattern: "\u65E5",
      examples: ["1\u65E5", "15\u65E5", "31\u65E5"]
    },
    dateFormatNotes: 'Japanese uses \u65E5 (nichi/day) after the day number: "2024\u5E745\u670815\u65E5" (year/month/day format)'
  }
};
var VIEW_TYPE_MILESTONE_TIMELINE = "milestone-timeline-view";

// src/views/MilestoneTimelineView.ts
var import_obsidian2 = require("obsidian");

// src/modals/HelpModal.ts
var import_obsidian = require("obsidian");
var MilestoneTimelineHelpModal = class extends import_obsidian.Modal {
  constructor(app) {
    super(app);
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("milestone-help-modal");
    const markdown = `
# Milestone Timeline help

## Quick start
- **Open Timeline:** Click the calendar-clock icon in the sidebar or use Command Palette
- **Click any milestone** to jump to that line in your note
- **Settings:** Configure in Settings \u2192 Milestone Timeline 2.0

## Supported date formats

**1. Frontmatter** (recommended for primary dates):
\`\`\`yaml
---
date: 2024-03-15
deadline: March 31, 2001
milestone: Aug 23 1931
dateFormat: International
dateUncertain: true
---
\`\`\`

**Obsidian Properties UI:** To use partial dates like "May 1985" in the Properties panel:
1. Click the property type icon next to the date field
2. Change **Property Type \u2192 Text**
3. Type "May 1985" directly

*The Date property type doesn't save incomplete dates to the file.*

**2. Inline dates:**
- \`2024-03-15\` - ISO format (unambiguous)
- \`March 31, 2001\` - Natural language (unambiguous)
- \`Aug 23 1931\` - Short month format (unambiguous)
- \`May 1985\` - Month Year (partial, defaults to 15th, marked uncertain)
- \`05/dd/1985\` - Obsidian incomplete date (day unknown, defaults to 15th, marked uncertain)
- \`1/2/1953\` - Numeric format (ambiguous - see settings)

**Year-only dates (explicit annotation required):**

To avoid ambiguity with page numbers or other 4-digit numbers, year-only dates must be explicitly tagged:

\`Published in #year/1809\` - Year-only date (defaults to July 1, marked uncertain)

**Use "Find Potential Year References"** command to quickly review and tag years in your notes!

**Partial/uncertain dates:**

Use \`dateUncertain: true\` for approximate dates. Partial dates (year-only or year-month) are automatically marked uncertain. Shows **~** indicator on the timeline.

**Numeric date ambiguity:**

\`1/2/1953\` could be Jan 2 (US) or Feb 1 (International). Set your preference in Settings \u2192 Date format preference. Override per-note with \`dateFormat\` in frontmatter.

**3. Wiki-link dates:**
\`\`\`
Important meeting: [[2024-03-15]]
\`\`\`

**4. Tag dates:**
\`\`\`
Contract signed #date/1987/02/18
Published in #year/1809
\`\`\`
*Use \`#year/YYYY\` for year-only dates to avoid ambiguity with page numbers.*

## Timeline features
- **Year markers:** Large badges marking each new year
- **Month markers:** Appear for years with many dates (configurable)
- **Heading context:** Shows the nearest section heading
- **Tag indicator:** icon for dates from tags
- **Uncertainty indicator:** **~** icon for approximate/partial dates
- **Click to navigate:** Opens note at exact line

## Key settings
- **Sort order:** Ascending (oldest first) or descending
- **Date format preference:** US (M/D/YYYY) or International (D/M/YYYY)
- **Language:** English, Spanish, French, Japanese for month names
- **Month threshold:** How many dates needed to show months (default: 10)
- **Exclude screenshots:** Filter out dates in image filenames
- **Include tag dates:** Toggle #date/YYYY/MM/DD and #year/YYYY support

## Useful commands
- **Find potential year references:** Scans notes for 4-digit numbers (1000-2100) that might be years. Helps you quickly add #year/ tags to meaningful dates.
- **Show help:** Opens this help dialog
- **Create example correspondence:** Creates sample notes to explore features

## Example note
\`\`\`markdown
---
date: 2024-01-15
dateFormat: International
---
# Project Timeline

## Planning
Started on Jan 15 2024

## Development  
- Kickoff: [[2024-02-01]]
- Beta release: #date/2024/05/20

## Launch
Final launch: 2024-07-01

## International Letter
Letter from London dated 1/2/1953 (Feb 1, 1953)
\`\`\`
*This note uses International date format, so 1/2/1953 = Feb 1!*

## Tips
- Use frontmatter for the main date of a note
- Headings provide context - organize notes with clear sections
- Screenshot dates are auto-filtered by default
- Lower month threshold for more detailed navigation
- Click Refresh button after changing settings

---

**Need more help?** Check the README.md file in the plugin folder for detailed documentation.
`;
    const component = new import_obsidian.Component();
    component.load();
    await import_obsidian.MarkdownRenderer.render(
      this.app,
      markdown,
      contentEl,
      "",
      component
    );
    const closeBtn = contentEl.createEl("button", { text: "Close" });
    closeBtn.setCssProps({ marginTop: "1em" });
    closeBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/views/MilestoneTimelineView.ts
var MilestoneTimelineView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.searchInput = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MILESTONE_TIMELINE;
  }
  getDisplayText() {
    return "Milestone Timeline";
  }
  getIcon() {
    return "calendar-clock";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("milestone-timeline-container");
    this.renderHeader(container);
    const timelineContent = container.createDiv("milestone-timeline-content");
    await this.renderTimelineContent(timelineContent);
  }
  renderHeader(container) {
    const header = container.createDiv("milestone-timeline-header");
    header.createEl("h4", { text: "Milestone Timeline" });
    const headerButtons = header.createDiv("milestone-header-buttons");
    const searchContainer = headerButtons.createDiv("milestone-search-container");
    this.searchInput = searchContainer.createEl("input", {
      type: "text",
      placeholder: "Search timeline...",
      cls: "milestone-search-input"
    });
    this.searchInput.addEventListener("input", (e) => {
      const target = e.target;
      const timelineContent = container.querySelector(".milestone-timeline-content");
      if (timelineContent) {
        void this.renderTimelineContent(timelineContent, target.value);
      }
    });
    const helpBtn = headerButtons.createEl("button", {
      text: "?",
      cls: "milestone-help-btn",
      attr: { "aria-label": "Help" }
    });
    helpBtn.addEventListener("click", () => {
      new MilestoneTimelineHelpModal(this.app).open();
    });
    const refreshBtn = headerButtons.createEl("button", {
      text: "Refresh",
      cls: "milestone-refresh-btn"
    });
    refreshBtn.addEventListener("click", () => {
      const timelineContent = container.querySelector(".milestone-timeline-content");
      if (timelineContent && this.searchInput) {
        void this.renderTimelineContent(timelineContent, this.searchInput.value);
      }
    });
  }
  async renderTimelineContent(timelineContent, searchQuery) {
    timelineContent.empty();
    const allMilestones = await this.extractMilestones();
    let milestones = allMilestones;
    if (searchQuery && searchQuery.trim().length > 0) {
      milestones = this.filterMilestones(allMilestones, searchQuery.trim());
    }
    if (milestones.length === 0) {
      const emptyMessage = searchQuery && searchQuery.trim().length > 0 ? `No milestones found matching "${searchQuery}". Found ${allMilestones.length} total milestones.` : "No milestones found. Add dates in your notes using formats like YYYY-MM-DD, [[YYYY-MM-DD]], or frontmatter.";
      timelineContent.createDiv({
        text: emptyMessage,
        cls: "milestone-empty-state"
      });
      return;
    }
    if (searchQuery && searchQuery.trim().length > 0) {
      const resultCount = timelineContent.createDiv("milestone-search-results");
      resultCount.setText(`Showing ${milestones.length} of ${allMilestones.length} milestones`);
    }
    milestones.sort((a, b) => {
      const order = this.plugin.settings.sortOrder === "asc" ? 1 : -1;
      return (a.date.getTime() - b.date.getTime()) * order;
    });
    const milestonesPerYear = /* @__PURE__ */ new Map();
    for (const milestone of milestones) {
      const year = milestone.date.getFullYear();
      milestonesPerYear.set(year, (milestonesPerYear.get(year) || 0) + 1);
    }
    const timeline = timelineContent.createDiv("milestone-timeline");
    let previousYear = null;
    let previousMonth = null;
    let currentYearHasMonthMarkers = false;
    for (const milestone of milestones) {
      const currentYear = milestone.date.getFullYear();
      const currentMonth = milestone.date.getMonth();
      const yearMilestoneCount = milestonesPerYear.get(currentYear) || 0;
      const shouldShowMonthMarkers = yearMilestoneCount >= this.plugin.settings.monthThreshold;
      const shouldShowYearMarkers = !this.plugin.settings.includeYearOnly || this.plugin.settings.showYearMarkersWithYearOnly;
      if (shouldShowYearMarkers && previousYear !== null && previousYear !== currentYear) {
        const yearMarker = timeline.createDiv("milestone-year-marker");
        const yearMarkerDot = yearMarker.createDiv("milestone-year-marker-dot");
        this.createSvgElement(yearMarkerDot, '<svg width="24" height="24" viewBox="0 0 24 24"><circle cx="12" cy="12" r="8" fill="currentColor"/><circle cx="12" cy="12" r="4" fill="var(--background-primary)"/></svg>');
        const yearContent = yearMarker.createDiv("milestone-year-content");
        yearContent.createDiv("milestone-year-line");
        yearContent.createDiv("milestone-year-label").setText(`${currentYear}`);
        yearContent.createDiv("milestone-year-line");
        previousMonth = null;
        currentYearHasMonthMarkers = shouldShowMonthMarkers;
      } else if (shouldShowYearMarkers && previousYear === null) {
        const yearMarker = timeline.createDiv("milestone-year-marker");
        const yearMarkerDot = yearMarker.createDiv("milestone-year-marker-dot");
        this.createSvgElement(yearMarkerDot, '<svg width="24" height="24" viewBox="0 0 24 24"><circle cx="12" cy="12" r="8" fill="currentColor"/><circle cx="12" cy="12" r="4" fill="var(--background-primary)"/></svg>');
        const yearContent = yearMarker.createDiv("milestone-year-content");
        yearContent.createDiv("milestone-year-line");
        yearContent.createDiv("milestone-year-label").setText(`${currentYear}`);
        yearContent.createDiv("milestone-year-line");
        currentYearHasMonthMarkers = shouldShowMonthMarkers;
      }
      if (currentYearHasMonthMarkers && (previousMonth === null || previousMonth !== currentMonth)) {
        const monthMarker = timeline.createDiv("milestone-month-marker");
        const monthMarkerDot = monthMarker.createDiv("milestone-month-marker-dot");
        this.createSvgElement(monthMarkerDot, '<svg width="16" height="16" viewBox="0 0 16 16"><rect x="4" y="4" width="8" height="8" fill="currentColor" rx="2"/></svg>');
        const monthLabel = monthMarker.createDiv("milestone-month-label");
        monthLabel.setText(this.getMonthName(currentMonth));
      }
      previousYear = currentYear;
      previousMonth = currentMonth;
      const item = timeline.createDiv("milestone-item");
      const marker = item.createDiv("milestone-marker");
      marker.createDiv("milestone-dot");
      const content = item.createDiv("milestone-content");
      const dateStr = this.formatMilestoneDate(milestone);
      const dateEl = content.createDiv("milestone-date");
      if (milestone.isUncertain) {
        dateEl.addClass("milestone-date-partial");
      }
      dateEl.setText(dateStr);
      if (milestone.isUncertain) {
        const uncertainIndicator = dateEl.createSpan("milestone-uncertain-indicator");
        uncertainIndicator.setText(" ~");
        uncertainIndicator.title = "Approximate or incomplete date";
      }
      if (milestone.isTag) {
        const tagIndicator = dateEl.createSpan("milestone-tag-indicator");
        this.createSvgElement(tagIndicator, '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><line x1="7" y1="7" x2="7.01" y2="7"/></svg>');
        tagIndicator.title = "From date tag";
      }
      if (this.plugin.settings.showFileLinks) {
        const titleEl = content.createEl("a", {
          text: milestone.title,
          cls: "milestone-title internal-link"
        });
        titleEl.setAttribute("data-href", milestone.file.path);
        titleEl.setAttribute("href", milestone.file.path);
        titleEl.addEventListener("mouseover", (e) => {
          this.app.workspace.trigger("hover-link", {
            event: e,
            source: "milestone-timeline",
            hoverParent: this,
            targetEl: titleEl,
            linktext: milestone.file.path,
            sourcePath: milestone.file.path
          });
        });
        titleEl.addEventListener("click", (e) => {
          e.preventDefault();
          e.stopPropagation();
          void (async () => {
            const leaf = this.app.workspace.getLeaf(false);
            await leaf.openFile(milestone.file);
            if (milestone.lineNumber !== void 0) {
              await new Promise((resolve) => globalThis.setTimeout(resolve, 100));
              const activeView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
              if (activeView && activeView.editor) {
                const editor = activeView.editor;
                editor.setCursor({ line: milestone.lineNumber, ch: 0 });
                editor.scrollIntoView({ from: { line: milestone.lineNumber, ch: 0 }, to: { line: milestone.lineNumber, ch: 0 } }, true);
              }
            }
          })();
        });
      } else {
        content.createDiv({
          text: milestone.title,
          cls: "milestone-title"
        });
      }
      if (milestone.heading) {
        content.createDiv({
          text: milestone.heading,
          cls: "milestone-heading"
        });
      }
      if (milestone.context) {
        const contextEl = content.createDiv({
          cls: "milestone-context"
        });
        this.renderWikiLinks(contextEl, milestone.context);
      }
    }
  }
  async extractMilestones() {
    const milestones = [];
    const files = this.app.vault.getMarkdownFiles();
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const extractedMilestones = this.extractDatesFromContent(content, file);
      milestones.push(...extractedMilestones);
    }
    return milestones;
  }
  filterMilestones(milestones, query) {
    const lowerQuery = query.toLowerCase();
    return milestones.filter((milestone) => {
      if (this.fuzzyMatch(milestone.title.toLowerCase(), lowerQuery)) {
        return true;
      }
      if (milestone.context && this.fuzzyMatch(milestone.context.toLowerCase(), lowerQuery)) {
        return true;
      }
      if (milestone.heading && this.fuzzyMatch(milestone.heading.toLowerCase(), lowerQuery)) {
        return true;
      }
      const dateStr = this.formatDate(milestone.date);
      if (this.fuzzyMatch(dateStr, lowerQuery)) {
        return true;
      }
      if (this.fuzzyMatch(milestone.file.path.toLowerCase(), lowerQuery)) {
        return true;
      }
      return false;
    });
  }
  fuzzyMatch(text, query) {
    let queryIndex = 0;
    for (let i = 0; i < text.length && queryIndex < query.length; i++) {
      if (text[i] === query[queryIndex]) {
        queryIndex++;
      }
    }
    return queryIndex === query.length || text.includes(query);
  }
  renderWikiLinks(contextEl, text) {
    const wikiLinkPattern = /\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g;
    let lastIndex = 0;
    let match;
    while ((match = wikiLinkPattern.exec(text)) !== null) {
      if (match.index > lastIndex) {
        contextEl.appendText(text.substring(lastIndex, match.index));
      }
      const linkPath = match[1];
      const displayText = match[2] || linkPath;
      const linkEl = contextEl.createEl("a", {
        text: displayText,
        cls: "internal-link"
      });
      linkEl.setAttribute("data-href", linkPath);
      linkEl.setAttribute("href", linkPath);
      linkEl.addEventListener("mouseover", (e) => {
        this.app.workspace.trigger("hover-link", {
          event: e,
          source: "milestone-timeline",
          hoverParent: this,
          targetEl: linkEl,
          linktext: linkPath,
          sourcePath: ""
        });
      });
      linkEl.addEventListener("click", (e) => {
        e.preventDefault();
        e.stopPropagation();
        void (async () => {
          const file = this.app.metadataCache.getFirstLinkpathDest(linkPath, "");
          if (file) {
            const leaf = this.app.workspace.getLeaf(false);
            await leaf.openFile(file);
          }
        })();
      });
      lastIndex = match.index + match[0].length;
    }
    if (lastIndex < text.length) {
      contextEl.appendText(text.substring(lastIndex));
    }
  }
  extractContentExcerpt(content, maxLength = 100) {
    const contentWithoutFrontmatter = content.replace(/^---\n[\s\S]*?\n---\n/, "");
    const contentWithoutComments = contentWithoutFrontmatter.replace(/%%[\s\S]*?%%/g, "");
    const lines = contentWithoutComments.split("\n");
    let excerpt = "";
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#") || trimmed.match(/^[-*_]{3,}$/)) {
        continue;
      }
      if (trimmed.match(/^!\[\[.*\]\]$/) || trimmed.match(/^\[\[.*\]\]$/)) {
        continue;
      }
      excerpt += (excerpt ? " " : "") + trimmed;
      if (excerpt.length >= maxLength) {
        break;
      }
    }
    if (excerpt.length > maxLength) {
      excerpt = excerpt.substring(0, maxLength) + "...";
    } else if (excerpt.length > 0 && excerpt.length < maxLength) {
      const hasMoreContent = contentWithoutComments.length > excerpt.length + 100;
      if (hasMoreContent) {
        excerpt += "...";
      }
    }
    return excerpt || "No content preview available";
  }
  parseDateMultiLocale(dateStr, formatPreference = "US", primaryLocale) {
    if (primaryLocale) {
      const result = this.parseDate(dateStr, formatPreference, primaryLocale);
      if (result) return result;
    }
    for (const localeName in LOCALIZATIONS) {
      const locale = LOCALIZATIONS[localeName];
      if (primaryLocale && locale === primaryLocale) continue;
      const result = this.parseDate(dateStr, formatPreference, locale);
      if (result) return result;
    }
    return null;
  }
  extractDatesFromContent(content, file) {
    var _a;
    const milestones = [];
    const seenDates = /* @__PURE__ */ new Set();
    const seenDateTimestamps = /* @__PURE__ */ new Set();
    const locale = LOCALIZATIONS[this.plugin.settings.language] || LOCALIZATIONS["en"];
    let noteDateFormatPreference = this.plugin.settings.dateFormatPreference;
    let isNoteUncertain = false;
    const frontmatterMatch = content.match(/^---\n([\s\S]*?)\n---/);
    if (frontmatterMatch) {
      const frontmatter = frontmatterMatch[1];
      const dateFormatMatch = frontmatter.match(/^dateFormat:\s*(.+)$/im);
      if (dateFormatMatch) {
        const formatValue = dateFormatMatch[1].trim().toLowerCase();
        if (formatValue === "us" || formatValue === "m/d/yyyy" || formatValue === "mdy") {
          noteDateFormatPreference = "US";
        } else if (formatValue === "international" || formatValue === "d/m/yyyy" || formatValue === "dmy") {
          noteDateFormatPreference = "International";
        }
      }
      const uncertainMatch = frontmatter.match(/^dateUncertain:\s*(.+)$/im);
      if (uncertainMatch) {
        const uncertainValue = uncertainMatch[1].trim().toLowerCase();
        isNoteUncertain = uncertainValue === "true" || uncertainValue === "yes";
      }
      const dateFields = ["date", "created", "modified", "milestone", "deadline", "due"];
      for (const field of dateFields) {
        const regex = new RegExp(`^${field}:\\s*(.+)$`, "im");
        const match = frontmatter.match(regex);
        if (match) {
          const dateStr = match[1].trim().replace(/^["']|["']$/g, "");
          const parseResult = this.parseDateMultiLocale(dateStr, noteDateFormatPreference, locale);
          if (parseResult) {
            const timestamp = parseResult.date.getTime();
            const key = `${timestamp}-frontmatter-${field}`;
            if (!seenDates.has(key)) {
              seenDates.add(key);
              seenDateTimestamps.add(timestamp);
              const excerpt = this.extractContentExcerpt(content);
              milestones.push({
                date: parseResult.date,
                title: file.basename,
                file,
                context: excerpt,
                // Note-level uncertain flag applies to frontmatter dates
                isUncertain: isNoteUncertain || parseResult.isPartial
              });
            }
          }
        }
      }
    }
    const contentWithoutFrontmatter = content.replace(/^---\n[\s\S]*?\n---\n/, "");
    const contentWithoutComments = contentWithoutFrontmatter.replace(/%%[\s\S]*?%%/g, "");
    const lines = contentWithoutComments.split("\n");
    const frontmatterLines = content.split("\n").length - contentWithoutComments.split("\n").length;
    let currentHeading = void 0;
    const isoPattern = /(?<!\[\[)\b(\d{4}-\d{1,2}-\d{1,2})\b(?!\]\])/g;
    const allLocalePatterns = [];
    for (const localeName in LOCALIZATIONS) {
      const loc = LOCALIZATIONS[localeName];
      const ordPattern = ((_a = loc.ordinalSuffixes) == null ? void 0 : _a.pattern) || "";
      const monthDayYear = ordPattern ? new RegExp(`\\b((${loc.monthPatterns.any})\\s+\\d{1,2}(?:${ordPattern})?,?\\s+\\d{4})\\b`, "gi") : new RegExp(`\\b((${loc.monthPatterns.any})\\s+\\d{1,2},?\\s+\\d{4})\\b`, "gi");
      allLocalePatterns.push({ pattern: monthDayYear, locale: loc });
      const monthYear = new RegExp(`\\b((${loc.monthPatterns.any})\\s+\\d{4})\\b`, "gi");
      allLocalePatterns.push({ pattern: monthYear, locale: loc });
    }
    const numericDatePattern = /\b(\d{1,2}[-/]\d{1,2}[-/]\d{4})\b/g;
    const numericDatePattern2Digit = /\b(\d{1,2}[-/]\d{1,2}[-/]\d{2})\b/g;
    const headingPattern = /^(#{1,6})\s+(.+)$/;
    const imageEmbedPattern = /!\[\[([^\]]+)\]\]/g;
    const tagDatePattern = /#date\/(\d{4})\/(\d{2})\/(\d{2})\b/g;
    const yearTagPattern = /#year\/(1[0-9]\d{2}|20\d{2}|2100)\b/g;
    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const actualLineNumber = i + frontmatterLines;
      const headingMatch = line.match(headingPattern);
      if (headingMatch) {
        currentHeading = headingMatch[2].trim();
        continue;
      }
      if (this.plugin.settings.includeTagDates) {
        tagDatePattern.lastIndex = 0;
        let tagMatch;
        while ((tagMatch = tagDatePattern.exec(line)) !== null) {
          const year = tagMatch[1];
          const month = tagMatch[2];
          const day = tagMatch[3];
          const dateStr = `${year}-${month}-${day}`;
          const parseResult = this.parseDate(dateStr, noteDateFormatPreference, locale);
          if (parseResult) {
            const timestamp = parseResult.date.getTime();
            if (seenDateTimestamps.has(timestamp)) {
              continue;
            }
            let context = line.replace(/^#+\s*/, "").trim();
            if (context.length > 100) {
              context = context.substring(0, 100) + "...";
            }
            const key = `${timestamp}-${i}-tag-${dateStr}`;
            if (!seenDates.has(key)) {
              seenDates.add(key);
              milestones.push({
                date: parseResult.date,
                title: file.basename,
                file,
                context,
                heading: currentHeading,
                lineNumber: actualLineNumber,
                isTag: true,
                // Only mark as uncertain if the date itself is partial
                isUncertain: parseResult.isPartial
              });
            }
          }
        }
      }
      if (this.plugin.settings.includeTagDates) {
        yearTagPattern.lastIndex = 0;
        let yearTagMatch;
        while ((yearTagMatch = yearTagPattern.exec(line)) !== null) {
          const year = yearTagMatch[1];
          const dateStr = `${year}-01-01`;
          const parseResult = this.parseDate(dateStr, noteDateFormatPreference, locale);
          if (parseResult) {
            const timestamp = parseResult.date.getTime();
            if (seenDateTimestamps.has(timestamp)) {
              continue;
            }
            let context = line.replace(/^#+\s*/, "").trim();
            if (context.length > 100) {
              context = context.substring(0, 100) + "...";
            }
            const key = `${timestamp}-${i}-yeartag-${year}`;
            if (!seenDates.has(key)) {
              seenDates.add(key);
              milestones.push({
                date: parseResult.date,
                title: file.basename,
                file,
                context,
                heading: currentHeading,
                lineNumber: actualLineNumber,
                isTag: true,
                // Mark as partial since it's year-only
                isUncertain: true
              });
            }
          }
        }
      }
      const universalPatterns = [
        { pattern: isoPattern, locale: null },
        { pattern: numericDatePattern, locale: null },
        { pattern: numericDatePattern2Digit, locale: null }
      ];
      const patterns = [...universalPatterns, ...allLocalePatterns];
      const matchedRanges = [];
      for (const patternInfo of patterns) {
        patternInfo.pattern.lastIndex = 0;
        let match;
        while ((match = patternInfo.pattern.exec(line)) !== null) {
          const dateStr = match[1];
          const matchIndex = match.index;
          const matchEnd = matchIndex + match[0].length;
          let overlaps = false;
          for (const range of matchedRanges) {
            if (matchIndex < range.end && matchEnd > range.start) {
              overlaps = true;
              break;
            }
          }
          if (overlaps) {
            continue;
          }
          if (this.plugin.settings.excludeScreenshots) {
            let isInImageEmbed = false;
            imageEmbedPattern.lastIndex = 0;
            let embedMatch;
            while ((embedMatch = imageEmbedPattern.exec(line)) !== null) {
              const embedStart = embedMatch.index;
              const embedEnd = embedStart + embedMatch[0].length;
              if (matchIndex >= embedStart && matchIndex < embedEnd) {
                isInImageEmbed = true;
                break;
              }
            }
            if (isInImageEmbed) {
              continue;
            }
          }
          const parseResult = patternInfo.locale ? this.parseDate(dateStr, noteDateFormatPreference, patternInfo.locale) : this.parseDateMultiLocale(dateStr, noteDateFormatPreference, locale);
          if (parseResult) {
            const timestamp = parseResult.date.getTime();
            if (seenDateTimestamps.has(timestamp)) {
              continue;
            }
            let context = line.replace(/^#+\s*/, "").trim();
            if (context.length > 100) {
              context = context.substring(0, 100) + "...";
            }
            const key = `${timestamp}-${i}-${context}`;
            if (!seenDates.has(key)) {
              seenDates.add(key);
              matchedRanges.push({ start: matchIndex, end: matchEnd });
              milestones.push({
                date: parseResult.date,
                title: file.basename,
                file,
                context,
                heading: currentHeading,
                lineNumber: actualLineNumber,
                // Only mark as uncertain if the date itself is partial
                isUncertain: parseResult.isPartial
              });
            }
          }
        }
      }
    }
    const allMonthPatterns = Object.values(LOCALIZATIONS).map((loc) => loc.monthPatterns.any).join("|");
    const wikiDatePattern = new RegExp(`\\[\\[([\\d-]+|(${allMonthPatterns})\\s+\\d{4})\\]\\]`, "gi");
    let wikiMatch;
    while ((wikiMatch = wikiDatePattern.exec(contentWithoutFrontmatter)) !== null) {
      const dateStr = wikiMatch[1];
      const parseResult = this.parseDateMultiLocale(dateStr, noteDateFormatPreference, locale);
      if (parseResult) {
        const context = `Wiki link: [[${dateStr}]]`;
        const key = `${parseResult.date.getTime()}-wiki-${dateStr}`;
        if (!seenDates.has(key)) {
          seenDates.add(key);
          milestones.push({
            date: parseResult.date,
            title: file.basename,
            file,
            context,
            // Only mark as uncertain if the date itself is partial
            isUncertain: parseResult.isPartial
          });
        }
      }
    }
    return milestones;
  }
  parseDate(dateStr, formatPreference = "US", locale) {
    var _a;
    if (!locale) {
      locale = LOCALIZATIONS["en"];
    }
    const cleanStr = dateStr.trim();
    let cleanedForParsing = cleanStr;
    if ((_a = locale.ordinalSuffixes) == null ? void 0 : _a.pattern) {
      const ordinalPattern = new RegExp(`(\\d{1,2})(${locale.ordinalSuffixes.pattern})\\b`, "gi");
      cleanedForParsing = cleanedForParsing.replace(ordinalPattern, "$1");
    }
    const hasPlaceholders = /(dd|DD|mm|MM|yyyy|YYYY)/i.test(cleanedForParsing);
    const incompleteDatePattern = /^(\d{1,2}|dd|DD|mm|MM)[-/](\d{1,2}|dd|DD|mm|MM)[-/](\d{4}|yyyy|YYYY)$/i;
    const incompleteMatch = cleanedForParsing.match(incompleteDatePattern);
    if (incompleteMatch && hasPlaceholders) {
      const first = incompleteMatch[1];
      const second = incompleteMatch[2];
      const third = incompleteMatch[3];
      if (third.toLowerCase() === "yyyy") {
        return null;
      }
      const year = parseInt(third);
      if (year < 1e3 || year > 2100) {
        return null;
      }
      let month = null;
      let day = 15;
      if (formatPreference === "US") {
        if (first.toLowerCase() === "mm") {
          month = 6;
        } else {
          month = parseInt(first);
        }
        if (second.toLowerCase() !== "dd") {
          day = parseInt(second);
        }
      } else {
        if (first.toLowerCase() !== "dd") {
          day = parseInt(first);
        }
        if (second.toLowerCase() === "mm") {
          month = 6;
        } else {
          month = parseInt(second);
        }
      }
      if (month < 1 || month > 12) {
        return null;
      }
      return { date: new Date(year, month - 1, day), isPartial: true };
    }
    const monthYearTextPattern = new RegExp(`^(${locale.monthPatterns.any})\\s+(\\d{4})$`, "i");
    const monthYearTextMatch = cleanedForParsing.match(monthYearTextPattern);
    if (monthYearTextMatch) {
      const monthStr = monthYearTextMatch[1];
      const year = parseInt(monthYearTextMatch[2]);
      const month = locale.monthNameMap[monthStr.toLowerCase()];
      if (month !== void 0 && year >= 1e3 && year <= 2100) {
        return { date: new Date(year, month, 15), isPartial: true };
      }
      return null;
    }
    const yearOnlyPattern = /^(\d{4})$/;
    const yearOnlyMatch = cleanedForParsing.match(yearOnlyPattern);
    if (yearOnlyMatch) {
      const year = parseInt(yearOnlyMatch[1]);
      if (year >= 1e3 && year <= 2100) {
        return { date: new Date(year, 6, 1), isPartial: true };
      }
      return null;
    }
    const yearMonthPattern = /^(\d{4})-(\d{1,2})$/;
    const yearMonthMatch = cleanedForParsing.match(yearMonthPattern);
    if (yearMonthMatch) {
      const year = parseInt(yearMonthMatch[1]);
      const month = parseInt(yearMonthMatch[2]);
      if (year >= 1e3 && year <= 2100 && month >= 1 && month <= 12) {
        return { date: new Date(year, month - 1, 15), isPartial: true };
      }
      return null;
    }
    const numericPattern = /^(\d{1,2})[-/](\d{1,2})[-/](\d{4})$/;
    const numericMatch = cleanedForParsing.match(numericPattern);
    if (numericMatch) {
      const first = parseInt(numericMatch[1]);
      const second = parseInt(numericMatch[2]);
      const year = parseInt(numericMatch[3]);
      let month, day;
      if (formatPreference === "US") {
        month = first;
        day = second;
      } else {
        day = first;
        month = second;
      }
      if (month >= 1 && month <= 12 && day >= 1 && day <= 31 && year >= 1e3 && year <= 2100) {
        const date2 = new Date(year, month - 1, day);
        if (date2.getFullYear() === year && date2.getMonth() === month - 1 && date2.getDate() === day) {
          return { date: date2, isPartial: false };
        }
      }
      return null;
    }
    const numericPattern2Digit = /^(\d{1,2})[-/](\d{1,2})[-/](\d{2})$/;
    const numericMatch2Digit = cleanedForParsing.match(numericPattern2Digit);
    if (numericMatch2Digit) {
      const first = parseInt(numericMatch2Digit[1]);
      const second = parseInt(numericMatch2Digit[2]);
      let yearShort = parseInt(numericMatch2Digit[3]);
      const year = yearShort >= 30 ? 1900 + yearShort : 2e3 + yearShort;
      let month, day;
      if (formatPreference === "US") {
        month = first;
        day = second;
      } else {
        day = first;
        month = second;
      }
      if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
        const date2 = new Date(year, month - 1, day);
        if (date2.getFullYear() === year && date2.getMonth() === month - 1 && date2.getDate() === day) {
          return { date: date2, isPartial: false };
        }
      }
      return null;
    }
    const date = new Date(cleanedForParsing);
    if (!isNaN(date.getTime())) {
      const year = date.getFullYear();
      if (year >= 1e3 && year <= 2100) {
        return { date, isPartial: false };
      }
    }
    return null;
  }
  formatDate(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  }
  formatMilestoneDate(milestone) {
    const date = milestone.date;
    const year = date.getFullYear();
    const month = date.getMonth();
    const day = date.getDate();
    if (milestone.isUncertain) {
      if (month === 6 && day === 1) {
        return `${year}`;
      }
      if (day === 15) {
        const locale = LOCALIZATIONS[this.plugin.settings.language] || LOCALIZATIONS["en"];
        const monthName = locale.monthNames.full[month];
        return `${monthName} ${year}`;
      }
    }
    return this.formatDate(date);
  }
  getMonthName(monthIndex) {
    const locale = LOCALIZATIONS[this.plugin.settings.language] || LOCALIZATIONS["en"];
    return locale.monthNames.full[monthIndex];
  }
  createSvgElement(container, svgString) {
    const parser = new DOMParser();
    const doc = parser.parseFromString(svgString, "image/svg+xml");
    const svgElement = doc.documentElement;
    if (svgElement && svgElement.tagName.toLowerCase() === "svg") {
      container.appendChild(svgElement);
    }
  }
  async onClose() {
  }
  async refresh() {
    const container = this.containerEl.children[1];
    if (container) {
      const timelineContent = container.querySelector(".milestone-timeline-content");
      if (timelineContent && this.searchInput) {
        await this.renderTimelineContent(timelineContent, this.searchInput.value);
      }
    }
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var MilestoneTimelineSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Display").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Sort order").setDesc("Sort milestones in ascending or descending order").addDropdown((dropdown) => dropdown.addOption("asc", "Ascending (oldest first)").addOption("desc", "Descending (newest first)").setValue(this.plugin.settings.sortOrder).onChange(async (value) => {
      this.plugin.settings.sortOrder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Show file links").setDesc("Make milestone titles clickable to open the source note").addToggle((toggle) => toggle.setValue(this.plugin.settings.showFileLinks).onChange(async (value) => {
      this.plugin.settings.showFileLinks = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Month marker threshold").setDesc("Show month markers within a year if it has at least this many milestones (default: 10)").addText((text) => text.setPlaceholder("10").setValue(String(this.plugin.settings.monthThreshold)).onChange(async (value) => {
      const numValue = parseInt(value);
      if (!isNaN(numValue) && numValue > 0) {
        this.plugin.settings.monthThreshold = numValue;
        await this.plugin.saveSettings();
      }
    }));
    new import_obsidian3.Setting(containerEl).setName("Exclude screenshot dates").setDesc('Ignore dates found in screenshot filenames like "screenshot 2025-11-07.png".').addToggle((toggle) => toggle.setValue(this.plugin.settings.excludeScreenshots).onChange(async (value) => {
      this.plugin.settings.excludeScreenshots = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Include tag dates").setDesc("Extract dates from tags in the format #date/YYYY/MM/DD").addToggle((toggle) => toggle.setValue(this.plugin.settings.includeTagDates).onChange(async (value) => {
      this.plugin.settings.includeTagDates = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Date format preference").setDesc('How to interpret ambiguous numeric dates like "1/2/1953". ISO dates (2024-03-15) and natural language dates remain unambiguous.').addDropdown((dropdown) => dropdown.addOption("US", "US (M/D/YYYY) - 1/2/1953 = Jan 2, 1953").addOption("International", "International (D/M/YYYY) - 1/2/1953 = Feb 1, 1953").setValue(this.plugin.settings.dateFormatPreference).onChange(async (value) => {
      this.plugin.settings.dateFormatPreference = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Language").setDesc('Language for month names and natural language date parsing. This affects how dates like "May 1985" or "Mayo 1985" are recognized.').addDropdown((dropdown) => dropdown.addOption("en", "English").addOption("es", "Espa\xF1ol (Spanish)").addOption("fr", "Fran\xE7ais (French)").addOption("ja", "\u65E5\u672C\u8A9E (Japanese)").setValue(this.plugin.settings.language).onChange(async (value) => {
      this.plugin.settings.language = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Include year-only dates").setDesc('Extract standalone year dates (like "1951") from note content. These are marked as uncertain since the exact date is unknown.').addToggle((toggle) => toggle.setValue(this.plugin.settings.includeYearOnly).onChange(async (value) => {
      this.plugin.settings.includeYearOnly = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.includeYearOnly) {
      new import_obsidian3.Setting(containerEl).setName("Show year markers with year-only dates").setDesc("When year-only extraction is enabled, display year markers in the timeline. Disable to reduce visual clutter.").addToggle((toggle) => toggle.setValue(this.plugin.settings.showYearMarkersWithYearOnly).onChange(async (value) => {
        this.plugin.settings.showYearMarkersWithYearOnly = value;
        await this.plugin.saveSettings();
      }));
    }
  }
};

// src/modals/PotentialYearsModal.ts
var import_obsidian4 = require("obsidian");
var PotentialYearsModal = class extends import_obsidian4.Modal {
  constructor(app, plugin, matches) {
    super(app);
    this.currentIndex = 0;
    this.plugin = plugin;
    this.matches = matches;
  }
  onOpen() {
    void this.renderMatch();
  }
  async renderMatch() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("milestone-years-modal");
    if (this.matches.length === 0) {
      const markdown = `
# All done!

No more potential year references to review.
`;
      const component2 = new import_obsidian4.Component();
      component2.load();
      await import_obsidian4.MarkdownRenderer.render(this.app, markdown, contentEl, "", component2);
      const closeBtn2 = contentEl.createEl("button", { text: "Close" });
      closeBtn2.addEventListener("click", () => this.close());
      return;
    }
    const match = this.matches[this.currentIndex];
    const header = contentEl.createDiv("potential-years-header");
    header.createEl("h2", { text: "Potential date reference" });
    header.createEl("span", {
      text: `${this.currentIndex + 1} / ${this.matches.length}`,
      cls: "potential-years-progress"
    });
    const yearDiv = contentEl.createDiv("potential-years-year-display");
    yearDiv.createEl("div", { text: match.year, cls: "potential-years-year-number" });
    const fileInfo = contentEl.createDiv("potential-years-file-info");
    const fileLink = fileInfo.createEl("a", { text: match.file.basename, cls: "potential-years-file-link" });
    fileLink.href = "#";
    fileLink.addEventListener("click", (e) => {
      e.preventDefault();
      const leaf = this.app.workspace.getLeaf(false);
      void leaf.openFile(match.file, { eState: { line: match.lineNumber - 1 } });
    });
    fileInfo.createEl("span", { text: ` (Line ${match.lineNumber})` });
    const contextDiv = contentEl.createDiv("potential-years-context");
    const highlightedContext = match.context.replace(
      new RegExp(`\\b${match.year}\\b`, "g"),
      `<mark>${match.year}</mark>`
    );
    contextDiv.innerHTML = highlightedContext;
    const instructions = `
**Is this an unstructured date reference that should be structured for your timeline?**

*Add #year/ tag to mark as a year-only date, or consider restructuring as a full date format (YYYY-MM-DD, "Month Day, Year", etc.)*
`;
    const instructionsDiv = contentEl.createDiv("potential-years-instructions");
    const component = new import_obsidian4.Component();
    component.load();
    await import_obsidian4.MarkdownRenderer.render(this.app, instructions, instructionsDiv, "", component);
    const actions = contentEl.createDiv("potential-years-actions");
    const yesBtn = actions.createEl("button", { text: "Add #year/ tag" });
    yesBtn.classList.add("mod-cta");
    yesBtn.addEventListener("click", () => {
      void this.addYearTag(match).then(() => {
        this.matches.splice(this.currentIndex, 1);
        if (this.currentIndex >= this.matches.length) {
          this.currentIndex = Math.max(0, this.matches.length - 1);
        }
        void this.renderMatch();
      });
    });
    const noBtn = actions.createEl("button", { text: "Skip" });
    noBtn.addEventListener("click", () => {
      this.matches.splice(this.currentIndex, 1);
      if (this.currentIndex >= this.matches.length) {
        this.currentIndex = Math.max(0, this.matches.length - 1);
      }
      void this.renderMatch();
    });
    const navDiv = contentEl.createDiv("potential-years-navigation");
    const prevBtn = navDiv.createEl("button", { text: "Previous" });
    prevBtn.disabled = this.currentIndex === 0;
    prevBtn.addEventListener("click", () => {
      if (this.currentIndex > 0) {
        this.currentIndex--;
        void this.renderMatch();
      }
    });
    const nextBtn = navDiv.createEl("button", { text: "Next" });
    nextBtn.disabled = this.currentIndex >= this.matches.length - 1;
    nextBtn.addEventListener("click", () => {
      if (this.currentIndex < this.matches.length - 1) {
        this.currentIndex++;
        void this.renderMatch();
      }
    });
    const closeBtn = navDiv.createEl("button", { text: "Close" });
    closeBtn.addEventListener("click", () => this.close());
  }
  async addYearTag(match) {
    const content = await this.app.vault.read(match.file);
    const lines = content.split("\n");
    if (match.lineNumber > 0 && match.lineNumber <= lines.length) {
      const line = lines[match.lineNumber - 1];
      const yearMatch = new RegExp(`\\b${match.year}\\b`).exec(line);
      if (yearMatch) {
        const before = line.substring(0, yearMatch.index + match.year.length);
        const after = line.substring(yearMatch.index + match.year.length);
        lines[match.lineNumber - 1] = `${before} #year/${match.year}${after}`;
        await this.app.vault.modify(match.file, lines.join("\n"));
        this.plugin.refreshOpenViews();
      }
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/modals/ExampleCreatedModal.ts
var import_obsidian5 = require("obsidian");
var ExampleCreatedModal = class extends import_obsidian5.Modal {
  constructor(app, message) {
    super(app);
    this.message = message;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("milestone-example-modal");
    const markdown = `
# Example correspondence created!

${this.message}

> **Try these features:**
> - Read authentic letters in French, German, Spanish, Japanese
> - Change Settings \u2192 Language and watch timeline update
> - Same letters work in ALL languages!
> - Click milestones to see original foreign language content
`;
    const component = new import_obsidian5.Component();
    component.load();
    await import_obsidian5.MarkdownRenderer.render(
      this.app,
      markdown,
      contentEl,
      "",
      component
    );
    const closeBtn = contentEl.createEl("button", { text: "Got it!" });
    closeBtn.setCssProps({ marginTop: "1em" });
    closeBtn.addEventListener("click", () => this.close());
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var MilestoneTimelinePlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_MILESTONE_TIMELINE,
      (leaf) => new MilestoneTimelineView(leaf, this)
    );
    this.addRibbonIcon("calendar-clock", "Open Milestone Timeline", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-timeline",
      name: "Open timeline",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "show-help",
      name: "Show help",
      callback: () => {
        new MilestoneTimelineHelpModal(this.app).open();
      }
    });
    this.addCommand({
      id: "create-example-correspondence",
      name: "Create example correspondence",
      callback: async () => {
        await this.createExampleCorrespondence();
      }
    });
    this.addCommand({
      id: "create-penpal-letters",
      name: "Create example: penpal letters (french)",
      callback: async () => {
        await this.createPenpalLetters();
      }
    });
    this.addCommand({
      id: "find-potential-years",
      name: "Find potential year references",
      callback: async () => {
        await this.findPotentialYears();
      }
    });
    this.addSettingTab(new MilestoneTimelineSettingTab(this.app, this));
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_MILESTONE_TIMELINE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({
          type: VIEW_TYPE_MILESTONE_TIMELINE,
          active: true
        });
      }
    }
    if (leaf) {
      void workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data || {});
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refreshOpenViews();
  }
  refreshOpenViews() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_MILESTONE_TIMELINE);
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof MilestoneTimelineView) {
        void view.refresh();
      }
    }
  }
  async createExampleCorrespondence() {
    const folderPath = "Milestone Timeline Examples";
    const { vault } = this.app;
    const existingFolder = vault.getAbstractFileByPath(folderPath);
    if (existingFolder) {
      new import_obsidian6.Notice("Example correspondence folder already exists. Creating additional example letters...");
    } else {
      await vault.createFolder(folderPath);
    }
    const letters = [
      {
        filename: "1947-03 - Lettre de Marie (Paris).md",
        content: `---
date: Mars 1947
dateUncertain: true
---

# Lettre de Marie Dubois

**De:** Paris, France  
**Date:** Mars 1947

---

Ch\xE8re amie,

Le printemps arrive \xE0 Paris et les marronniers commencent \xE0 fleurir le long de la Seine. La ville se r\xE9veille lentement apr\xE8s ces ann\xE9es difficiles.

Je pense visiter en Ao\xFBt 1947 si je peux organiser le voyage.

Les caf\xE9s rouvrent un par un, et on entend \xE0 nouveau de la musique dans les rues.

Amicalement,  
Marie

---

*[Original letter in French - dates automatically detected regardless of your timeline language setting]*

#correspondence #france`
      },
      {
        filename: "1952-05 - Brief von Hans (Berlin).md",
        content: `---
date: Mai 1952
dateUncertain: true
---

# Brief von Hans Schmidt

**Von:** Berlin, Deutschland  
**Datum:** Mai 1952

---

Liebe Freundin,

Ich schreibe Ihnen aus dem wiederaufgebauten Berlin. Die Universit\xE4t hat mir eine neue Position angeboten, und ich bin sehr aufgeregt \xFCber diese M\xF6glichkeit.

Eine wichtige Konferenz ist f\xFCr Juli 1952 geplant. Ich hoffe, Sie k\xF6nnen teilnehmen.

Die Stadt ver\xE4ndert sich jeden Tag. Wo letztes Jahr noch Tr\xFCmmer standen, erheben sich jetzt neue Geb\xE4ude.

Mit freundlichen Gr\xFC\xDFen,  
Hans

---

*[Original letter in German - Mai (May) detected and shown in your timeline]*

#correspondence #germany`
      },
      {
        filename: "1958-08 - \u7530\u4E2D\u3055\u3093\u304B\u3089\u306E\u624B\u7D19 (Tokyo).md",
        content: `---
date: 8\u6708 1958
dateUncertain: true
---

# \u7530\u4E2D\u3086\u304D\u304B\u3089\u306E\u624B\u7D19

**\u304B\u3089:** \u6771\u4EAC\u3001\u65E5\u672C  
**\u65E5\u4ED8:** 1958\u5E748\u6708

---

\u89AA\u611B\u306A\u308B\u53CB\u4EBA\u3078\u3001

\u304A\u76C6\u306E\u5B63\u7BC0\u306B\u306A\u308A\u307E\u3057\u305F\u3002\u6771\u4EAC\u306F1964\u5E74\u306E\u30AA\u30EA\u30F3\u30D4\u30C3\u30AF\u306E\u6E96\u5099\u3067\u5927\u304D\u304F\u5909\u308F\u3063\u3066\u3044\u307E\u3059\u3002

\u7956\u6BCD\u306F\u3053\u306E\u90FD\u5E02\u3092\u8A8D\u8B58\u3057\u306A\u3044\u3067\u3057\u3087\u3046\u3002\u3059\u3079\u3066\u304C\u65B0\u3057\u304F\u3001\u3059\u3079\u3066\u304C\u5909\u5316\u3057\u3066\u3044\u307E\u3059\u3002

8\u670815\u65E5\u306B\u304A\u76C6\u306E\u796D\u308A\u304C\u3042\u308A\u307E\u3057\u305F\u3002\u3068\u3066\u3082\u7F8E\u3057\u304B\u3063\u305F\u3067\u3059\u3002

\u656C\u5177\u3001  
\u3086\u304D

---

*[Original letter in Japanese - 8\u6708 (August) automatically parsed]*

#correspondence #japan`
      },
      {
        filename: "1963-03 - Carta de Carlos (Madrid).md",
        content: `---
date: Marzo 1963
dateUncertain: true
---

# Carta de Carlos Ruiz

**De:** Madrid, Espa\xF1a  
**Fecha:** Marzo 1963

---

Querida amiga,

Te escribo desde Madrid donde trabajo como periodista. Los tiempos son dif\xEDciles pero importantes.

Publiqu\xE9 un art\xEDculo importante el 7 de Marzo de 1963 sobre la libertad de prensa.

Las palabras tienen poder, pero tambi\xE9n peligro. Cada d\xEDa escribo con cuidado pero con verdad.

Un abrazo fuerte,  
Carlos

---

*[Original letter in Spanish - Marzo (March) recognized in any timeline language]*

#correspondence #spain`
      },
      {
        filename: "1968-05 - Lettre de Marie (Mai 68).md",
        content: `---
date: Mai 1968
---

# Lettre Urgente de Marie

**De:** Paris, France  
**Date:** 28 Mai 1968

---

Mon amie,

J'\xE9cris rapidement. Les rues de Paris sont remplies d'\xE9tudiants et de manifestants. C'est Mai 68 - l'histoire se fait dans nos rues!

Les \xE9v\xE9nements du 28 Mai 1968 seront dans tous les livres d'histoire.

Les voix demandent le changement. L'universit\xE9 est ferm\xE9e. La ville vibre d'\xE9nergie r\xE9volutionnaire.

Je joins des affiches que j'ai trouv\xE9es.

Solidairement,  
Marie

---

*[Mai 68 - French date formatting preserved in original context]*

#correspondence #france #mai-68`
      },
      {
        filename: "1975 - Letzter Brief von Hans.md",
        content: `---
date: 1975
dateUncertain: true
---

# Letzter Brief von Hans Schmidt

**Von:** Berlin, Deutschland  
**Datum:** 1975 (genaues Datum unbekannt)

---

Meine alte Freundin,

Dies wird wahrscheinlich mein letzter Brief sein. Ich bin m\xFCde, aber dankbar.

Drei\xDFig Jahre Briefe - ein Leben voller Freundschaft, bewahrt in Papier und Tinte.

Danke f\xFCr jedes Wort, jede Erinnerung, jede geteilte Geschichte.

Berlin und Paris, Tokyo und Madrid - wir haben die Welt durch unsere Briefe verbunden.

In Freundschaft f\xFCr immer,  
Hans

---

*[Only year known - demonstrates year-only date handling]*

#correspondence #germany #memorial`
      },
      {
        filename: "_README - Multilingual Timeline Demo.md",
        content: `---
date: 2024-01-15
---

# \u{1F30D} Multilingual Timeline Demonstration

This collection showcases the **Milestone Timeline plugin's internationalization capabilities**.

## What This Demonstrates

### \u{1F4DD} Original Letters in Native Languages

Each letter is written in its **original language** with **native date formats**:

- \u{1F1EB}\u{1F1F7} **French:** "Mars 1947", "Mai 1968"
- \u{1F1E9}\u{1F1EA} **German:** "Mai 1952", "Juli 1952"
- \u{1F1EF}\u{1F1F5} **Japanese:** "8\u6708 1958" (8-gatsu = August)
- \u{1F1EA}\u{1F1F8} **Spanish:** "Marzo 1963"

### \u{1F504} Automatic Date Parsing

The plugin **automatically detects and parses** dates regardless of language:

1. \u2705 French "Mars 1947" \u2192 Parsed as March 1947
2. \u2705 Spanish "Marzo 1963" \u2192 Parsed as March 1963
3. \u2705 German "Mai 1952" \u2192 Parsed as May 1952
4. \u2705 Japanese "8\u6708" \u2192 Parsed as August

### \u{1F3AF} Your Timeline, Your Language

**Open the Milestone Timeline** and see all dates displayed correctly!

**Then try this:**
1. Go to Settings \u2192 Milestone Timeline \u2192 **Language**
2. Change to Spanish \u2192 Timeline shows "Mayo", "Marzo"
3. Change to French \u2192 Timeline shows "Mai", "Mars"
4. Change to Japanese \u2192 Timeline shows "5\u6708", "3\u6708"

**The same letters work in ALL languages!**

## \u{1F393} How It Works

The plugin:
1. **Parses** dates written in any supported language
2. **Normalizes** them to standard dates
3. **Displays** timeline markers in YOUR selected language
4. **Preserves** original content unchanged

## \u{1F4CA} Timeline Features Shown

- **Year markers:** 1947 \u2192 1975 (spanning decades)
- **Month markers:** Multiple letters in same year
- **Uncertainty indicators (~):** Approximate dates
- **Language mixing:** French, German, Spanish, Japanese together
- **Date formats:** Year-only, Month-Year, complete dates

## \u{1F4A1} Real-World Use Case

Perfect for:
- Historical document collections
- International correspondence archives
- Research across multiple languages
- Preserving original language context
- Multilingual family history projects

## \u{1F9EA} Try These Experiments

1. **Switch languages** and watch timeline update
2. **Click milestones** to jump to original letters
3. **Notice** how "Mai" (French/German) is the same month
4. **See** uncertainty markers (~) on approximate dates
5. **Observe** authentic foreign language content preserved

---

**Note:** This demonstrates the plugin's ability to work with real multilingual content. The same notes work correctly regardless of your timeline language setting.

Delete the "Milestone Timeline Examples" folder when you're done exploring!

#example #internationalization #multilingual #timeline-demo`
      }
    ];
    let createdCount = 0;
    for (const letter of letters) {
      const filePath = `${folderPath}/${letter.filename}`;
      try {
        await vault.create(filePath, letter.content);
        createdCount++;
      } catch (e) {
      }
    }
    if (createdCount > 0) {
      const indexPath = `${folderPath}/_README - Multilingual Timeline Demo.md`;
      const indexFile = vault.getAbstractFileByPath(indexPath);
      if (indexFile instanceof import_obsidian6.TFile) {
        const leaf = this.app.workspace.getLeaf(false);
        void leaf.openFile(indexFile);
      }
      await this.activateView();
      const message = `Created ${createdCount} authentic multilingual letters in "${folderPath}" folder.

These are REAL foreign language letters with native dates (French "Mars", Spanish "Marzo", Japanese "8\u6708").

The timeline is now open. Try changing Settings \u2192 Language to see the same letters displayed in different locales!`;
      new ExampleCreatedModal(this.app, message).open();
    }
  }
  async createPenpalLetters() {
    const folderPath = "Grandparent Letters/Correspondence with Am\xE9lie";
    const { vault } = this.app;
    const existingFolder = vault.getAbstractFileByPath(folderPath);
    if (existingFolder) {
      new import_obsidian6.Notice("Am\xE9lie's correspondence folder already exists. Overwriting existing letters...");
    } else {
      await vault.createFolder("Grandparent Letters").catch(() => {
      });
      await vault.createFolder(folderPath).catch(() => {
      });
    }
    const letters = [
      {
        filename: "1956-04-12 - First Letter from Paris.md",
        content: `---
date: 12 Avril 1956
location: Paris, France
from: Am\xE9lie Rousseau
---

# Ma premi\xE8re lettre

**Paris, le 12 Avril 1956**

Ch\xE8re amie,

C'est avec une grande joie que je t'\xE9cris cette premi\xE8re lettre depuis Paris! Nous nous sommes rencontr\xE9es il y a seulement trois semaines lors de ce merveilleux s\xE9jour \xE0 [[Nice]], mais j'ai l'impression de te conna\xEEtre depuis toujours.

La vie \xE0 Paris est exactement comme je l'avais imagin\xE9e - effervescente, bruyante, magnifique. Chaque matin, je traverse le [[Pont des Arts]] pour me rendre \xE0 mon travail \xE0 la librairie. L'odeur des livres anciens et du caf\xE9 frais me rappelle nos conversations nocturnes sur la terrasse de l'h\xF4tel.

Je pense souvent \xE0 notre promesse de rester en contact. Le monde semble si vaste parfois, mais ces lettres nous rapprocheront, j'en suis certaine.

Avec toute mon affection,  
**Am\xE9lie**

---

*My dearest friend, this is the beginning of what would become a lifelong correspondence across continents and decades.*

#correspondence #paris #1950s`
      },
      {
        filename: "1963-08-15 - Summer in Provence.md",
        content: `---
date: 15 Ao\xFBt 1963
location: Avignon, Provence
from: Am\xE9lie Rousseau
---

# \xC9t\xE9 en Provence

**Avignon, le 15 Ao\xFBt 1963**

Ma tr\xE8s ch\xE8re amie,

Sept ann\xE9es ont pass\xE9 depuis ma premi\xE8re lettre! Le temps file si vite. Je t'\xE9cris aujourd'hui depuis la maison de campagne de ma tante en Provence. Les champs de lavande s'\xE9tendent \xE0 perte de vue, et le soleil d'ao\xFBt rend tout dor\xE9 et parfait.

Tu te souviens que je t'avais parl\xE9 de [[Jean-Pierre Dubois|Jean-Pierre]]? Eh bien, nous nous sommes mari\xE9s au printemps! Le 3 Mai 1963, pour \xEAtre pr\xE9cise. C'\xE9tait une petite c\xE9r\xE9monie intime dans une chapelle pr\xE8s de [[Montmartre]]. J'aurais tant aim\xE9 que tu sois l\xE0.

Jean-Pierre est professeur de litt\xE9rature. Il me lit de la po\xE9sie tous les soirs avant de dormir. Hier soir, c'\xE9tait [[Baudelaire]] - "L'Invitation au voyage". Tu aurais ador\xE9.

Comment va ta vie de l'autre c\xF4t\xE9 de l'oc\xE9an? Tes lettres me manquent. La derni\xE8re date de mars dernier.

Je t'embrasse tendrement,  
**Am\xE9lie**

P.S. - J'ai joint quelques graines de lavande. Plante-les en pensant \xE0 moi!

#correspondence #provence #marriage #1960s`
      },
      {
        filename: "1978-11-03 - Autumn Reflections.md",
        content: `---
date: 3 Novembre 1978
location: Paris, France
from: Am\xE9lie Rousseau-Dubois
---

# R\xE9flexions d'automne

**Paris, le 3 Novembre 1978**

Mon amie de toujours,

Les feuilles tombent sur les boulevards parisiens, et je me retrouve \xE0 penser \xE0 toutes ces ann\xE9es pass\xE9es. Vingt-deux ans d'amiti\xE9 \xE0 travers ces lettres! N'est-ce pas extraordinaire?

Les enfants grandissent si vite. [[Sophie Dubois|Sophie]] a maintenant quinze ans - elle te ressemble, tu sais. La m\xEAme d\xE9termination dans les yeux. [[Thomas Dubois|Thomas]] vient d'avoir douze ans la semaine derni\xE8re, le 27 Octobre 1978. Il veut devenir \xE9crivain, comme son p\xE8re.

Jean-Pierre et moi avons emmen\xE9 les enfants \xE0 [[Londres]] cet \xE9t\xE9. Sophie a ador\xE9 le [[British Museum]], tandis que Thomas n'a voulu visiter que les librairies de [[Charing Cross Road]]. Nous avons pens\xE9 \xE0 toi constamment - tu nous avais tant parl\xE9 de ta visite l\xE0-bas dans ta lettre de 1971.

Le monde change rapidement autour de nous. Parfois je me sens d\xE9pass\xE9e par tout ce progr\xE8s. Mais ta constante amiti\xE9 reste un phare dans ma vie.

Avec toute ma tendresse,  
**Am\xE9lie**

P.S. - Sophie a dessin\xE9 un portrait de notre famille. Je te l'envoie s\xE9par\xE9ment.

#correspondence #family #paris #1970s`
      },
      {
        filename: "1995-12-20 - Memories and Hope.md",
        content: `---
date: 20 D\xE9cembre 1995
location: Paris, France
from: Am\xE9lie Rousseau-Dubois
---

# Souvenirs et espoir

**Paris, le 20 D\xE9cembre 1995**

Ma plus ch\xE8re et plus vieille amie,

Pr\xE8s de quarante ans d'amiti\xE9! Qui aurait cru, lors de cette rencontre fortuite \xE0 [[Nice]] en 1956, que nous \xE9changerions encore des lettres \xE0 la fin du si\xE8cle?

Jean-Pierre a pris sa retraite le mois dernier, le 15 Novembre 1995. Nous parlons de voyager davantage. L'Am\xE9rique, peut-\xEAtre? Apr\xE8s toutes ces ann\xE9es de correspondance, il est temps que nous nous revoyions en personne, tu ne crois pas?

Sophie est maintenant m\xE9decin \xE0 [[Lyon]]. Elle s'est mari\xE9e l'ann\xE9e derni\xE8re \xE0 un homme merveilleux nomm\xE9 [[Dr. Michel Fontaine|Michel]]. Thomas vit \xE0 [[Montr\xE9al]] - il a publi\xE9 son premier roman cette ann\xE9e! "Les Lettres de l'Atlantique" - inspir\xE9, dit-il, par toutes les histoires que je lui racontais de notre correspondance.

Le monde est devenu si petit avec tous ces ordinateurs et t\xE9l\xE9phones portables. Les jeunes n'\xE9crivent plus de lettres comme nous le faisions. Ils ne savent pas ce qu'ils manquent - l'anticipation, le plaisir de tenir une enveloppe, de reconna\xEEtre l'\xE9criture d'un ami...

Je garde pr\xE9cieusement chacune de tes lettres dans une bo\xEEte en bois que Jean-Pierre m'a offerte. Elles sont mon tr\xE9sor le plus pr\xE9cieux.

Joyeux No\xEBl, mon amie. J'esp\xE8re que le nouveau mill\xE9naire nous apportera cette rencontre tant attendue.

Avec tout mon amour,  
**Am\xE9lie**

P.S. - Ci-joint une photo r\xE9cente de toute la famille lors de Thanksgiving. Oui, nous c\xE9l\xE9brons Thanksgiving maintenant - ton influence apr\xE8s toutes ces ann\xE9es! \u{1F60A}

#correspondence #millennium #family #reflection #1990s`
      }
    ];
    let createdCount = 0;
    for (const letter of letters) {
      const filePath = `${folderPath}/${letter.filename}`;
      try {
        await vault.create(filePath, letter.content);
        createdCount++;
      } catch (e) {
        try {
          await vault.adapter.write(filePath, letter.content);
          createdCount++;
        } catch (e2) {
        }
      }
    }
    if (createdCount > 0) {
      const firstLetterPath = `${folderPath}/${letters[0].filename}`;
      const firstLetter = vault.getAbstractFileByPath(firstLetterPath);
      if (firstLetter instanceof import_obsidian6.TFile) {
        const leaf = this.app.workspace.getLeaf(false);
        void leaf.openFile(firstLetter);
      }
      await this.activateView();
      const message = `Created ${createdCount} letters from Am\xE9lie spanning 1956-1995!

\u{1F4EE} This is a personal correspondence collection showing:
\u2022 Authentic French dates (12 Avril 1956, 15 Ao\xFBt 1963)
\u2022 Life events across 4 decades
\u2022 References to people and places (using wiki-links)
\u2022 The evolution of a friendship through letters

The timeline is now open. Notice how all French dates are automatically parsed and displayed in your preferred language!`;
      new ExampleCreatedModal(this.app, message).open();
    }
  }
  async findPotentialYears() {
    const { vault } = this.app;
    const files = vault.getMarkdownFiles();
    const yearPattern = /(?<![\d-/])(?<!-)(?<!\/)(?<!\[\[)(?<!#year\/)\b(1[0-9]\d{2}|20\d{2}|2100)\b(?![\d-/])(?!--)(?!\]\])/g;
    const matches = [];
    for (const file of files) {
      const content = await vault.cachedRead(file);
      let contentWithoutFrontmatter = content;
      if (content.startsWith("---")) {
        const endOfFrontmatter = content.indexOf("\n---", 3);
        if (endOfFrontmatter !== -1) {
          contentWithoutFrontmatter = content.substring(endOfFrontmatter + 4);
        }
      }
      const contentWithoutComments = contentWithoutFrontmatter.replace(/%%[\s\S]*?%%/g, "");
      const lines = contentWithoutComments.split("\n");
      for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        yearPattern.lastIndex = 0;
        let match;
        while ((match = yearPattern.exec(line)) !== null) {
          const year = match[1];
          const matchIndex = match.index;
          const matchEnd = matchIndex + year.length;
          const contextStart = Math.max(0, matchIndex - 20);
          const contextEnd = Math.min(line.length, matchEnd + 20);
          const surroundingText = line.substring(contextStart, contextEnd);
          let isPartOfStructuredDate = false;
          if (/\d{4}-\d{1,2}(-\d{1,2})?/.test(surroundingText)) {
            isPartOfStructuredDate = true;
          } else if (/\d{1,2}\/\d{1,2}\/\d{2,4}/.test(surroundingText)) {
            isPartOfStructuredDate = true;
          } else if (/(January|February|March|April|May|June|July|August|September|October|November|December|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Oct|Nov|Dec)/i.test(surroundingText)) {
            isPartOfStructuredDate = true;
          } else if (/(Enero|Febrero|Marzo|Abril|Mayo|Junio|Julio|Agosto|Septiembre|Octubre|Noviembre|Diciembre|Ene|Abr|Ago|Dic)/i.test(surroundingText)) {
            isPartOfStructuredDate = true;
          } else if (/(Janvier|Février|Mars|Avril|Mai|Juin|Juillet|Août|Septembre|Octobre|Novembre|Décembre|Fév|Avr|Aoû|Déc)/i.test(surroundingText)) {
            isPartOfStructuredDate = true;
          } else if (/[0-9]+月/.test(surroundingText)) {
            isPartOfStructuredDate = true;
          } else if (/(st|nd|rd|th|º|ª|°|er|ère|ème|eme|日)/.test(surroundingText)) {
            isPartOfStructuredDate = true;
          } else if (/#(date|year)\//.test(surroundingText)) {
            isPartOfStructuredDate = true;
          } else if (/(dd|mm)\/\d{1,2}\/\d{2,4}/i.test(surroundingText) || /\d{1,2}\/(dd|mm)\/\d{2,4}/i.test(surroundingText)) {
            isPartOfStructuredDate = true;
          }
          if (isPartOfStructuredDate) {
            continue;
          }
          let context = line.trim();
          if (context.length > 80) {
            const matchPos = match.index;
            const start = Math.max(0, matchPos - 40);
            const end = Math.min(line.length, matchPos + 40);
            context = (start > 0 ? "..." : "") + line.substring(start, end).trim() + (end < line.length ? "..." : "");
          }
          matches.push({
            year,
            file,
            lineNumber: i + 1,
            context
          });
        }
      }
    }
    if (matches.length === 0) {
      new ExampleCreatedModal(this.app, "No unstructured date references found in your notes.\n\nThis searches for 4-digit numbers (1000-2100) that might be dates but aren't already captured by structured date patterns (ISO dates, month names, date tags, etc.).\n\nThis helps you identify and structure ambiguous date references.").open();
    } else {
      new PotentialYearsModal(this.app, this, matches).open();
    }
  }
};
