/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => WeeklyMealPlannerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/types/types.ts
var DEFAULT_SETTINGS = {
  recipeFolderPath: "Recipes",
  mealsPerWeek: 7,
  weeksToGenerate: 1,
  daysOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
  enableSeasonality: false,
  hemisphere: "northern",
  dayConstraints: {},
  skipKidMealIfFamilyFriendly: true,
  generateShoppingList: true,
  mealPlanFolderPath: "Meals",
  mealPlanTags: ["meal_plan"],
  minRating: void 0,
  // No minimum rating by default (includes all recipes)
  dayEmojis: {
    monday: "\u{1F319}",
    tuesday: "\u{1F525}",
    wednesday: "\u{1F42A}",
    thursday: "\u26A1",
    friday: "\u{1F389}",
    saturday: "\u{1F31F}",
    sunday: "\u2600\uFE0F",
    default: "\u{1F4C5}"
  },
  difficultyEmojis: {
    easy: "\u{1F7E2}",
    medium: "\u{1F7E1}",
    hard: "\u{1F534}",
    default: "\u26AA"
  }
};

// src/settings/SettingsTab.ts
var import_obsidian = require("obsidian");
var FolderSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputElement = inputEl;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((folder) => {
      if (folder instanceof import_obsidian.TFolder && folder.path.toLowerCase().contains(lowerCaseInputStr)) {
        folders.push(folder);
      }
    });
    return folders.slice(0, 10);
  }
  renderSuggestion(folder, el) {
    el.createEl("div", { text: folder.path });
  }
  selectSuggestion(folder) {
    this.inputElement.value = folder.path;
    this.inputElement.trigger("input");
    this.close();
  }
};
var MealPlannerSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.showTimeConstraints = false;
    this.showDifficultyConstraints = false;
    this.showKidMealOptions = false;
    this.plugin = plugin;
  }
  // =========================
  // Settings Tab UI for Meal Planner Plugin
  // =========================
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Recipe folder path").setDesc("Path to folder containing your recipe notes").addText((text) => {
      text.setPlaceholder("Recipes").setValue(this.plugin.settings.recipeFolderPath).onChange(async (value) => {
        this.plugin.settings.recipeFolderPath = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    new import_obsidian.Setting(containerEl).setName("Meal plan folder path").setDesc("Path to folder where generated meal plan files are stored").addText((text) => {
      text.setPlaceholder("Meals").setValue(this.plugin.settings.mealPlanFolderPath || "Meals").onChange(async (value) => {
        this.plugin.settings.mealPlanFolderPath = value;
        await this.plugin.saveSettings();
      });
      new FolderSuggest(this.app, text.inputEl);
    });
    new import_obsidian.Setting(containerEl).setName("Meal plan note tags").setDesc("Comma-separated list of tags to include in the frontmatter of generated meal plan notes.").addText(
      (text) => text.setPlaceholder("Meal, weekly, food").setValue((this.plugin.settings.mealPlanTags || ["meal_plan"]).join(", ")).onChange(async (value) => {
        this.plugin.settings.mealPlanTags = value.split(",").map((t) => t.trim()).filter(Boolean);
        if (this.plugin.settings.mealPlanTags.length === 0) {
          this.plugin.settings.mealPlanTags = ["meal_plan"];
        }
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Meals per week").setDesc("Number of meals to plan per week").addDropdown((dropdown) => {
      for (let i = 1; i <= 7; i++) {
        dropdown.addOption(String(i), String(i));
      }
      dropdown.setValue(String(this.plugin.settings.mealsPerWeek || 7));
      dropdown.onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.mealsPerWeek = num;
          await this.plugin.saveSettings();
        }
      });
    });
    new import_obsidian.Setting(containerEl).setName("Weeks to generate").setDesc("Number of weeks to include in the meal plan").addDropdown((dropdown) => {
      for (let i = 1; i <= 4; i++) {
        dropdown.addOption(String(i), String(i));
      }
      dropdown.setValue(String(this.plugin.settings.weeksToGenerate || 1));
      dropdown.onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.weeksToGenerate = num;
          await this.plugin.saveSettings();
        }
      });
    });
    new import_obsidian.Setting(containerEl).setName("Generate shopping list").setDesc("Include a shopping list section in the generated meal plan note.").addToggle(
      (toggle) => toggle.setTooltip("Generate shopping list").setValue(this.plugin.settings.generateShoppingList).onChange(async (value) => {
        this.plugin.settings.generateShoppingList = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Minimum recipe rating").setDesc("Only include recipes with this rating or higher. Unrated recipes are always included. Leave empty to include all recipes.").addDropdown((dropdown) => {
      dropdown.addOption("", "No minimum");
      for (let i = 1; i <= 5; i++) {
        const stars = "\u2605".repeat(i);
        dropdown.addOption(String(i), `${i} ${stars}`);
      }
      dropdown.setValue(this.plugin.settings.minRating ? String(this.plugin.settings.minRating) : "");
      dropdown.onChange(async (value) => {
        if (value === "") {
          this.plugin.settings.minRating = void 0;
        } else {
          const num = parseInt(value);
          if (!isNaN(num) && num >= 1 && num <= 5) {
            this.plugin.settings.minRating = num;
          }
        }
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Seasonality").setDesc("Only select recipes that are in season for the current time of year.").addToggle(
      (toggle) => toggle.setTooltip("Consider seasonality").setValue(this.plugin.settings.enableSeasonality).onChange(async (value) => {
        this.plugin.settings.enableSeasonality = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.enableSeasonality) {
      new import_obsidian.Setting(containerEl).setName("Hemisphere").setDesc("Set your hemisphere to correctly determine seasons.").addDropdown(
        (dropdown) => dropdown.addOption("northern", "Northern").addOption("southern", "Southern").setValue(this.plugin.settings.hemisphere).onChange(async (value) => {
          this.plugin.settings.hemisphere = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Time constraints").setDesc("Set maximum cooking time (in minutes) for each day of the week.").addToggle(
      (toggle) => toggle.setValue(this.showTimeConstraints).onChange(async (value) => {
        this.showTimeConstraints = value;
        if (!value) {
          this.plugin.settings.daysOfWeek.forEach((day) => {
            if (this.plugin.settings.dayConstraints[day]) {
              delete this.plugin.settings.dayConstraints[day].maxTime;
            }
          });
          await this.plugin.saveSettings();
        }
        this.display();
      })
    );
    if (this.showTimeConstraints) {
      this.plugin.settings.daysOfWeek.forEach((day) => {
        const constraints = this.plugin.settings.dayConstraints[day] || {};
        const shortDay = day.substring(0, 3);
        new import_obsidian.Setting(containerEl).setName(shortDay).addText(
          (text) => text.setPlaceholder("Minutes").setValue(constraints.maxTime ? String(constraints.maxTime) : "").onChange(async (value) => {
            if (!this.plugin.settings.dayConstraints[day]) {
              this.plugin.settings.dayConstraints[day] = {};
            }
            if (value === "") {
              delete this.plugin.settings.dayConstraints[day].maxTime;
            } else {
              const num = parseInt(value);
              if (!isNaN(num) && num > 0) {
                this.plugin.settings.dayConstraints[day].maxTime = num;
              }
            }
            await this.plugin.saveSettings();
          })
        );
      });
    }
    new import_obsidian.Setting(containerEl).setName("Difficulty constraints").setDesc("Set maximum difficulty level for each day of the week.").addToggle(
      (toggle) => toggle.setValue(this.showDifficultyConstraints).onChange(async (value) => {
        this.showDifficultyConstraints = value;
        if (!value) {
          this.plugin.settings.daysOfWeek.forEach((day) => {
            if (this.plugin.settings.dayConstraints[day]) {
              delete this.plugin.settings.dayConstraints[day].maxDifficulty;
            }
          });
          await this.plugin.saveSettings();
        }
        this.display();
      })
    );
    if (this.showDifficultyConstraints) {
      this.plugin.settings.daysOfWeek.forEach((day) => {
        const constraints = this.plugin.settings.dayConstraints[day] || {};
        const shortDay = day.substring(0, 3);
        new import_obsidian.Setting(containerEl).setName(shortDay).addDropdown(
          (dropdown) => dropdown.addOption("", "Any").addOption("easy", "Easy").addOption("medium", "Easy-medium").setValue(constraints.maxDifficulty || "").onChange(async (value) => {
            if (!this.plugin.settings.dayConstraints[day]) {
              this.plugin.settings.dayConstraints[day] = {};
            }
            if (value === "") {
              delete this.plugin.settings.dayConstraints[day].maxDifficulty;
            } else {
              this.plugin.settings.dayConstraints[day].maxDifficulty = value;
            }
            await this.plugin.saveSettings();
          })
        );
      });
    }
    new import_obsidian.Setting(containerEl).setName("Kid's meal").setDesc("Toggle whether to include a separate kid meal for each day.").addToggle(
      (toggle) => toggle.setValue(this.showKidMealOptions).onChange(async (value) => {
        this.showKidMealOptions = value;
        if (!value) {
          this.plugin.settings.daysOfWeek.forEach((day) => {
            if (this.plugin.settings.dayConstraints[day]) {
              delete this.plugin.settings.dayConstraints[day].needsKidMeal;
            }
          });
          await this.plugin.saveSettings();
        }
        this.display();
      })
    );
    if (this.showKidMealOptions) {
      this.plugin.settings.daysOfWeek.forEach((day) => {
        const constraints = this.plugin.settings.dayConstraints[day] || {};
        const shortDay = day.substring(0, 3);
        new import_obsidian.Setting(containerEl).setName(shortDay).addToggle(
          (toggle) => toggle.setTooltip("Include kid meal").setValue(constraints.needsKidMeal || false).onChange(async (value) => {
            if (!this.plugin.settings.dayConstraints[day]) {
              this.plugin.settings.dayConstraints[day] = {};
            }
            this.plugin.settings.dayConstraints[day].needsKidMeal = value;
            if (!value) {
              delete this.plugin.settings.dayConstraints[day].needsKidMeal;
            }
            await this.plugin.saveSettings();
          })
        );
      });
      new import_obsidian.Setting(containerEl).setName("Skip kid meal if family friendly").setDesc("Skip the kid's meal if a family-friendly meal is chosen for that day.").addToggle(
        (toggle) => toggle.setTooltip("Skip kid meal").setValue(this.plugin.settings.skipKidMealIfFamilyFriendly).onChange(async (value) => {
          this.plugin.settings.skipKidMealIfFamilyFriendly = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian.Setting(containerEl).setName("Day icons").setDesc("Set custom icons for each day of the week.").setHeading();
    this.plugin.settings.daysOfWeek.forEach((day) => {
      const shortDay = day.substring(0, 3);
      new import_obsidian.Setting(containerEl).setName(shortDay).addText(
        (text) => text.setPlaceholder("Icon").setValue(this.plugin.settings.dayEmojis[day.toLowerCase()] || "").onChange(async (value) => {
          this.plugin.settings.dayEmojis[day.toLowerCase()] = value || "";
          await this.plugin.saveSettings();
        })
      );
    });
    new import_obsidian.Setting(containerEl).setName("Recipe difficulty level").setDesc("Set custom icons for recipe difficulty levels.").setHeading();
    const difficultyKeys = ["easy", "medium", "hard", "default"];
    difficultyKeys.forEach((level) => {
      new import_obsidian.Setting(containerEl).setName(level.charAt(0).toUpperCase() + level.slice(1)).setDesc(level === "default" ? "For unknown difficulty" : ``).addText(
        (text) => text.setPlaceholder("Icon").setValue(this.plugin.settings.difficultyEmojis[level] || "").onChange(async (value) => {
          this.plugin.settings.difficultyEmojis[level] = value || "";
          await this.plugin.saveSettings();
        })
      );
    });
  }
};

// src/modals/Modals.ts
var import_obsidian3 = require("obsidian");

// src/utils/MealPlanUtils.ts
var import_obsidian2 = require("obsidian");
async function extractMealPlanChecklistEntries(app, settings, filePath) {
  const file = app.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(filePath));
  if (!(file instanceof import_obsidian2.TFile))
    return [];
  const content = await app.vault.cachedRead(file);
  const lines = content.split(/\r?\n/);
  const entries = [];
  let currentWeek = 1;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const weekMatch = line.match(/^### (?:📅 )?Week (\d+)/);
    if (weekMatch) {
      currentWeek = parseInt(weekMatch[1], 10);
      continue;
    }
    const checklistMatch = line.match(/^- \[.\] \*\*(.+?)\s([A-Za-z]+)\*\* - (.+)$/u);
    if (checklistMatch) {
      const dayEmoji = checklistMatch[1].trim();
      const day = checklistMatch[2].trim();
      const recipesRaw = checklistMatch[3];
      const recipes = Array.from(recipesRaw.matchAll(/\[\[([^\]]+)\]\]/g)).map((m) => m[1]);
      entries.push({
        week: currentWeek,
        day,
        dayEmoji,
        line,
        lineIndex: i,
        recipes
      });
    }
  }
  return entries;
}

// src/modals/Modals.ts
var SwapMealsModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.onSubmit = onSubmit;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Swap meals between days" });
    const mealPlanPath = this.plugin.settings.currentMealPlanPath;
    if (!mealPlanPath) {
      contentEl.createEl("div", { text: "No active meal plan found." });
      return;
    }
    const entries = await extractMealPlanChecklistEntries(this.app, this.plugin.settings, mealPlanPath);
    if (entries.length < 2) {
      contentEl.createEl("div", { text: "Not enough meals to swap." });
      return;
    }
    let selectedEntry1 = entries[0];
    let selectedEntry2 = entries[1];
    new import_obsidian3.Setting(contentEl).setName("Meal #1").addDropdown((dropdown) => {
      entries.forEach((entry, idx) => {
        const label = `Week ${entry.week} - ${entry.day}: ${entry.recipes.join(" & ")}`;
        dropdown.addOption(idx.toString(), label);
      });
      dropdown.onChange((value) => {
        selectedEntry1 = entries[parseInt(value, 10)];
      });
      dropdown.setValue("0");
    });
    new import_obsidian3.Setting(contentEl).setName("Meal #2").addDropdown((dropdown) => {
      entries.forEach((entry, idx) => {
        const label = `Week ${entry.week} - ${entry.day}: ${entry.recipes.join(" & ")}`;
        dropdown.addOption(idx.toString(), label);
      });
      dropdown.onChange((value) => {
        selectedEntry2 = entries[parseInt(value, 10)];
      });
      dropdown.setValue("1");
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Swap").setCta().onClick(() => {
      this.close();
      this.onSubmit(selectedEntry1, selectedEntry2);
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var KidMealPromptModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, kidMeals, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.kidMeals = kidMeals;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add a kid's meal?" });
    contentEl.createEl("div", { text: "The selected recipe is not family or kid friendly, but this day requires a kid meal. Would you like to add one?" });
    let selectedKidMeal = this.kidMeals.length > 0 ? this.kidMeals[0].name : null;
    if (this.kidMeals.length > 0) {
      new import_obsidian3.Setting(contentEl).setName("Select kid meal").addDropdown((dropdown) => {
        this.kidMeals.forEach((recipe) => {
          dropdown.addOption(recipe.name, recipe.name);
        });
        dropdown.onChange((value) => selectedKidMeal = value);
        dropdown.setValue(selectedKidMeal || "");
      });
    }
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Add kid's meal").setCta().onClick(() => {
      this.close();
      this.onSubmit(selectedKidMeal);
    })).addExtraButton((btn) => btn.setIcon("cross").setTooltip("No kid meal").onClick(() => {
      this.close();
      this.onSubmit(null);
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ChangeMealModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, onSubmit) {
    super(app);
    this.plugin = plugin;
    this.onSubmit = onSubmit;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Change meal" });
    const mealPlanPath = this.plugin.settings.currentMealPlanPath;
    if (!mealPlanPath) {
      contentEl.createEl("div", { text: "No active meal plan found." });
      return;
    }
    const entries = await extractMealPlanChecklistEntries(this.app, this.plugin.settings, mealPlanPath);
    if (entries.length === 0) {
      contentEl.createEl("div", { text: "No meals found in the current meal plan." });
      return;
    }
    let selectedEntry = entries[0];
    let selectedRecipe = "";
    let selectedChecklistLine = entries[0].line;
    const recipes = (await this.plugin.getRecipesBound()).slice().sort((a, b) => a.name.localeCompare(b.name));
    new import_obsidian3.Setting(contentEl).setName("Select meal to change").addDropdown((dropdown) => {
      entries.forEach((entry, idx) => {
        const label = `Week ${entry.week} - ${entry.day}: ${entry.recipes.join(" & ")}`;
        dropdown.addOption(idx.toString(), label);
      });
      dropdown.onChange((value) => {
        selectedEntry = entries[parseInt(value, 10)];
        selectedChecklistLine = selectedEntry.line;
      });
      dropdown.setValue("0");
    });
    new import_obsidian3.Setting(contentEl).setName("Select new recipe").addDropdown((dropdown) => {
      recipes.forEach((recipe) => {
        dropdown.addOption(recipe.name, recipe.name);
      });
      dropdown.onChange((value) => selectedRecipe = value);
      if (recipes.length > 0)
        selectedRecipe = recipes[0].name;
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Change meal").setCta().onClick(() => {
      const recipe = recipes.find((r) => r.name === selectedRecipe);
      const dayConstraints = this.plugin.settings.dayConstraints[selectedEntry.day];
      const needsKidMeal = dayConstraints == null ? void 0 : dayConstraints.needsKidMeal;
      const isNotFriendly = recipe && !recipe.familyFriendly && !recipe.kidFriendly;
      if (needsKidMeal && isNotFriendly) {
        const kidMeals = recipes.filter((r) => !!r.kidFriendly && !r.familyFriendly);
        new KidMealPromptModal(this.app, this.plugin, kidMeals, (kidMealName) => {
          this.close();
          this.onSubmit(selectedEntry.week, selectedEntry.day, selectedRecipe, selectedChecklistLine, kidMealName);
        }).open();
      } else {
        this.close();
        this.onSubmit(selectedEntry.week, selectedEntry.day, selectedRecipe, selectedChecklistLine);
      }
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var OverwriteOrNewFileModal = class extends import_obsidian3.Modal {
  constructor(app, filePath, onOverwrite, onCreateNew) {
    super(app);
    this.filePath = filePath;
    this.onOverwrite = onOverwrite;
    this.onCreateNew = onCreateNew;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Meal plan file exists" });
    contentEl.createEl("div", { text: `A meal plan file already exists at: ${this.filePath}` });
    new import_obsidian3.Setting(contentEl).addButton((btn) => btn.setButtonText("Overwrite").setCta().onClick(() => {
      this.close();
      const result = this.onOverwrite();
      if (result instanceof Promise) {
        result.catch(console.error);
      }
    })).addButton((btn) => btn.setButtonText("Create new").onClick(() => {
      this.close();
      const result = this.onCreateNew();
      if (result instanceof Promise) {
        result.catch(console.error);
      }
    })).addExtraButton((btn) => btn.setIcon("cross").setTooltip("Cancel").onClick(() => {
      this.close();
    }));
  }
  onClose() {
    this.contentEl.empty();
  }
};
var RecipeNameModal = class extends import_obsidian3.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.recipeName = "";
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Create new recipe" });
    new import_obsidian3.Setting(contentEl).setName("Recipe name").setDesc("Enter a name for your new recipe").addText((text) => {
      text.setPlaceholder("Spaghetti and meatballs").setValue(this.recipeName).onChange((value) => {
        this.recipeName = value;
      });
      text.inputEl.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
          this.submit();
        }
      });
      setTimeout(() => text.inputEl.focus(), 10);
    });
    new import_obsidian3.Setting(contentEl).addButton(
      (btn) => btn.setButtonText("Create recipe").setCta().onClick(() => this.submit())
    ).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.close();
        this.onSubmit("");
      })
    );
  }
  submit() {
    if (this.recipeName.trim()) {
      this.close();
      this.onSubmit(this.recipeName.trim());
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/utils/RecipeUtils.ts
var import_obsidian4 = require("obsidian");
function getDifficultyLevel(difficulty) {
  switch (difficulty == null ? void 0 : difficulty.toLowerCase()) {
    case "easy":
      return 1;
    case "medium":
      return 2;
    case "hard":
      return 3;
    default:
      return 2;
  }
}
function getDifficultyEmoji(difficulty, settings) {
  const key = (difficulty == null ? void 0 : difficulty.toLowerCase()) || "default";
  return settings.difficultyEmojis[key] || settings.difficultyEmojis["default"] || "\u26AA";
}
function getDayEmoji(day, settings) {
  const key = day.toLowerCase();
  return settings.dayEmojis[key] || settings.dayEmojis["default"] || "\u{1F4C5}";
}
function getRecipeTotalTime(recipe) {
  const prep = recipe.prepTime || 0;
  const cook = recipe.cookTime || 0;
  return prep + cook;
}
function scoreRecipe(recipe, alreadySelected, currentDayIndex, selectedArray) {
  let score = 100;
  if (recipe.rating !== void 0 && recipe.rating !== null) {
    const ratingBonus = Math.max(0, (recipe.rating - 1) * 3);
    score += ratingBonus;
  }
  const exactMatches = alreadySelected.filter((selected) => selected.file.path === recipe.file.path).length;
  if (exactMatches > 0) {
    score -= exactMatches * 75 * (exactMatches + 1);
  }
  if (typeof currentDayIndex === "number" && selectedArray) {
    const recentRange = 3;
    for (let checkIndex = Math.max(0, currentDayIndex - recentRange); checkIndex < currentDayIndex; checkIndex++) {
      if (selectedArray[checkIndex] && selectedArray[checkIndex].file.path === recipe.file.path) {
        const dayDistance = currentDayIndex - checkIndex;
        score -= Math.max(25, 100 / dayDistance);
      }
    }
  }
  if (recipe.lastUsed) {
    const daysSinceUsed = (Date.now() - recipe.lastUsed) / (1e3 * 60 * 60 * 24);
    if (daysSinceUsed < 7) {
      score -= (7 - daysSinceUsed) * 10;
    } else if (daysSinceUsed < 14) {
      score -= (14 - daysSinceUsed) * 2;
    }
    score += Math.min(daysSinceUsed * 1, 30);
  } else {
    score += 25;
  }
  const overlapPenalty = alreadySelected.reduce((penalty, selected) => {
    const overlap = recipe.ingredients.filter(
      (ing) => selected.ingredients.some(
        (selIng) => ing.toLowerCase().includes(selIng.toLowerCase()) || selIng.toLowerCase().includes(ing.toLowerCase())
      )
    ).length;
    return penalty + overlap * 5;
  }, 0);
  score -= overlapPenalty;
  if (typeof currentDayIndex === "number" && selectedArray) {
    const prevDayIndex = currentDayIndex - 1;
    if (prevDayIndex >= 0 && selectedArray[prevDayIndex]) {
      const prevRecipe = selectedArray[prevDayIndex];
      if (prevRecipe.file.path === recipe.file.path) {
        return -9999;
      } else if (prevRecipe.meal_type && recipe.meal_type && prevRecipe.meal_type === recipe.meal_type) {
        score -= 30;
      }
    }
    const nextDayIndex = currentDayIndex + 1;
    if (nextDayIndex < selectedArray.length && selectedArray[nextDayIndex]) {
      const nextRecipe = selectedArray[nextDayIndex];
      if (nextRecipe.file.path === recipe.file.path) {
        return -9999;
      } else if (nextRecipe.meal_type && recipe.meal_type && nextRecipe.meal_type === recipe.meal_type) {
        score -= 30;
      }
    }
  } else {
    if (recipe.meal_type && alreadySelected.length > 0) {
      const lastRecipe = alreadySelected[alreadySelected.length - 1];
      if (lastRecipe.meal_type && lastRecipe.meal_type === recipe.meal_type) {
        score -= 30;
      }
    }
    if (alreadySelected.length > 0) {
      const lastRecipe = alreadySelected[alreadySelected.length - 1];
      if (lastRecipe.name.toLowerCase() === recipe.name.toLowerCase()) {
        return -9999;
      }
    }
  }
  if (recipe.difficulty === "easy")
    score += 10;
  if (recipe.difficulty === "hard")
    score -= 5;
  score += Math.random() * 10;
  return score;
}
function meetsConstraints(recipe, day, constraints, isKidMeal = false) {
  const dayConstraints = constraints[day];
  if (!dayConstraints)
    return true;
  if (isKidMeal) {
    if (!recipe.kidFriendly)
      return false;
    if (recipe.familyFriendly)
      return false;
  }
  if (!isKidMeal && dayConstraints.needsKidMeal) {
    if (recipe.kidFriendly && !recipe.familyFriendly)
      return false;
  }
  if (!isKidMeal && dayConstraints.maxTime) {
    const totalTime = getRecipeTotalTime(recipe);
    if (totalTime > 0 && totalTime > dayConstraints.maxTime)
      return false;
  }
  if (!isKidMeal && dayConstraints.maxDifficulty) {
    const recipeLevel = getDifficultyLevel(recipe.difficulty);
    const maxLevel = getDifficultyLevel(dayConstraints.maxDifficulty);
    if (recipeLevel > maxLevel)
      return false;
  }
  return true;
}
function normalizeSeason(season) {
  const seasons = Array.isArray(season) ? season : [season];
  return seasons.map((s) => {
    const normalized = s.toLowerCase().trim();
    if (normalized.includes("spring"))
      return "spring";
    if (normalized.includes("summer"))
      return "summer";
    if (normalized.includes("fall") || normalized.includes("autumn"))
      return "fall";
    if (normalized.includes("winter"))
      return "winter";
    return normalized;
  }).filter((s) => ["spring", "summer", "fall", "winter"].includes(s));
}
function extractIngredients(content) {
  const ingredientSection = content.match(/##(?:\s*\p{Emoji})?\s*Ingredients\n([\s\S]*?)(?=\n##|$)/iu);
  if (!ingredientSection)
    return [];
  return ingredientSection[1].split("\n").filter((line) => line.trim().startsWith("-")).map((line) => line.replace(/^-\s*/, "").trim());
}
function extractTime(content, type) {
  const regex = type === "prep" ? /prep time:?\s*(\d+)/i : /cook time:?\s*(\d+)/i;
  const match = content.match(regex);
  return match ? parseInt(match[1]) : void 0;
}
function extractDifficulty(content) {
  const match = content.match(/difficulty:?\s*(easy|medium|hard)/i);
  return match ? match[1].toLowerCase() : void 0;
}
async function getRecipes(app, settings) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p;
  const recipes = [];
  const normalizedRecipeFolderPath = (0, import_obsidian4.normalizePath)(settings.recipeFolderPath);
  const folder = app.vault.getAbstractFileByPath(normalizedRecipeFolderPath);
  if (!folder) {
    new import_obsidian4.Notice(`Recipe folder "${settings.recipeFolderPath}" not found!`);
    return recipes;
  }
  const files = app.vault.getMarkdownFiles().filter(
    (file) => file.path.startsWith(normalizedRecipeFolderPath)
  );
  for (const file of files) {
    const content = await app.vault.cachedRead(file);
    const cache = app.metadataCache.getFileCache(file);
    const recipe = {
      file,
      name: file.basename,
      tags: ((_a = cache == null ? void 0 : cache.tags) == null ? void 0 : _a.map((t) => t.tag.slice(1))) || [],
      ingredients: extractIngredients(content),
      prepTime: ((_d = (_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.prep_time) != null ? _d : (_c = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _c.prepTime) || extractTime(content, "prep"),
      cookTime: ((_g = (_e = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _e.cook_time) != null ? _g : (_f = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _f.cookTime) || extractTime(content, "cook"),
      difficulty: ((_h = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _h.difficulty) || extractDifficulty(content),
      lastUsed: (_i = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _i.lastUsed,
      season: ((_j = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _j.season) ? normalizeSeason((_k = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _k.season) : void 0,
      kidFriendly: ((_l = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _l.kid_friendly) || false,
      familyFriendly: ((_m = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _m.family_friendly) || false,
      meal_type: (_o = (_n = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _n.meal_type) == null ? void 0 : _o.toLowerCase(),
      rating: (_p = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _p.rating
    };
    if (settings.minRating !== void 0) {
      if (recipe.rating !== void 0 && recipe.rating < settings.minRating) {
        continue;
      }
    }
    recipes.push(recipe);
  }
  return recipes;
}

// src/core/MealPlanService.ts
var import_obsidian5 = require("obsidian");

// src/strategies/RecipeSelectionStrategies.ts
function selectBestRecipe(pool, alreadySelected) {
  if (pool.length === 0)
    return void 0;
  const shuffledPool = pool.slice();
  for (let i = shuffledPool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffledPool[i], shuffledPool[j]] = [shuffledPool[j], shuffledPool[i]];
  }
  const scored = shuffledPool.map((recipe) => ({
    recipe,
    // Score against ALL selected recipes to avoid ingredient overlap
    score: scoreRecipe(recipe, alreadySelected)
  }));
  scored.sort((a, b) => b.score - a.score);
  const topScore = scored[0].score;
  const topRecipes = scored.filter((r) => r.score === topScore);
  const chosen = topRecipes[Math.floor(Math.random() * topRecipes.length)].recipe;
  return chosen;
}
var FamilyFriendlyStrategy = (recipes, day, settings, selected, isKidMeal) => {
  const dayConstraints = settings.dayConstraints[day];
  if (isKidMeal || !(dayConstraints == null ? void 0 : dayConstraints.needsKidMeal) || !settings.skipKidMealIfFamilyFriendly) {
    return void 0;
  }
  const familyRecipes = recipes.filter(
    (r) => r.familyFriendly && meetsConstraints(r, day, settings.dayConstraints, false) && // Main meal constraints
    !selected.includes(r)
  );
  return selectBestRecipe(familyRecipes, selected);
};
var RegularMealStrategy = (recipes, day, settings, selected, isKidMeal) => {
  const validRecipes = recipes.filter((r) => {
    if (!meetsConstraints(r, day, settings.dayConstraints, isKidMeal)) {
      return false;
    }
    if (selected.includes(r)) {
      return false;
    }
    if (!isKidMeal && r.kidFriendly && !r.familyFriendly) {
      return false;
    }
    return true;
  });
  return selectBestRecipe(validRecipes, selected);
};
var LastResortStrategy = (recipes, day, settings, selected, _isKidMeal) => {
  const remaining = recipes.filter((r) => !selected.includes(r));
  const nonKidOnly = remaining.filter((r) => !(r.kidFriendly && !r.familyFriendly));
  const poolToUse = nonKidOnly.length > 0 ? nonKidOnly : remaining;
  return selectBestRecipe(poolToUse, selected);
};
var KidMealStrategy = (kidFriendlyRecipes, day, settings, allSelected, isKidMeal, thisWeekKidMeals = []) => {
  let validRecipes = kidFriendlyRecipes.filter(
    (r) => meetsConstraints(r, day, settings.dayConstraints, true) && !thisWeekKidMeals.includes(r) && !allSelected.includes(r)
    // Check against allSelected for overall uniqueness
  );
  if (validRecipes.length === 0) {
    validRecipes = kidFriendlyRecipes.filter(
      (r) => meetsConstraints(r, day, settings.dayConstraints, true) && !allSelected.includes(r)
    );
  }
  if (validRecipes.length === 0) {
    validRecipes = kidFriendlyRecipes.filter(
      (r) => !allSelected.includes(r)
    );
  }
  if (validRecipes.length === 0) {
    validRecipes = kidFriendlyRecipes;
  }
  if (validRecipes.length > 0) {
    return selectBestRecipe(validRecipes, thisWeekKidMeals);
  }
  return void 0;
};

// src/core/MealPlanService.ts
var mainMealStrategies = [
  FamilyFriendlyStrategy,
  RegularMealStrategy,
  LastResortStrategy
];
function selectRecipes(recipes, count, days, kidMealIndices, settings) {
  if (recipes.length === 0)
    return { regularMeals: [], kidMeals: /* @__PURE__ */ new Map() };
  const selected = new Array(count).fill(void 0);
  const assignedRecipes = /* @__PURE__ */ new Set();
  const indicesWithFamilyMeals = /* @__PURE__ */ new Set();
  const eligiblePools = [];
  for (let i = 0; i < count; i++) {
    const dayIndex = i % days.length;
    const day = days[dayIndex];
    let pool = [];
    for (const strategy of mainMealStrategies) {
      const availableRecipes = recipes.filter((r) => !assignedRecipes.has(r));
      const selectedRecipe = strategy(availableRecipes, day, settings, selected.filter(Boolean), false);
      if (selectedRecipe) {
        pool = [selectedRecipe];
        break;
      }
    }
    if (pool.length === 0) {
      pool = recipes.filter(
        (r) => !assignedRecipes.has(r) && meetsConstraints(r, day, settings.dayConstraints, false) && (!r.kidFriendly || r.familyFriendly)
      );
    }
    eligiblePools.push(pool);
  }
  for (let i = 0; i < count; i++) {
    let pool = eligiblePools[i].filter((r) => !assignedRecipes.has(r));
    pool = pool.filter((recipe) => {
      const prevDayIndex = i - 1;
      if (prevDayIndex >= 0 && selected[prevDayIndex]) {
        const prevRecipe = selected[prevDayIndex];
        if (prevRecipe.file.path === recipe.file.path) {
          return false;
        }
      }
      const nextDayIndex = i + 1;
      if (nextDayIndex < selected.length && selected[nextDayIndex]) {
        const nextRecipe = selected[nextDayIndex];
        if (nextRecipe.file.path === recipe.file.path) {
          return false;
        }
      }
      return true;
    });
    if (pool.length === 0) {
      pool = eligiblePools[i].filter((r) => !assignedRecipes.has(r));
    }
    const scored = pool.map((recipe) => ({
      recipe,
      score: scoreRecipe(recipe, selected.filter(Boolean), i, selected)
    }));
    scored.sort((a, b) => b.score - a.score);
    if (scored.length > 0) {
      const topScore = scored[0].score;
      const topRecipes = scored.filter((r) => r.score === topScore);
      const chosen = topRecipes[Math.floor(Math.random() * topRecipes.length)].recipe;
      selected[i] = chosen;
      assignedRecipes.add(chosen);
      if (chosen.familyFriendly)
        indicesWithFamilyMeals.add(i);
      else if (chosen.kidFriendly && !chosen.familyFriendly && kidMealIndices[i])
        indicesWithFamilyMeals.add(i);
    }
  }
  for (let i = 0; i < count; i++) {
    if (!selected[i]) {
      const dayIndex = i % days.length;
      const day = days[dayIndex];
      let pool = recipes.filter(
        (r) => meetsConstraints(r, day, settings.dayConstraints, false) && (!r.kidFriendly || r.familyFriendly)
      );
      pool = pool.filter((recipe) => {
        const prevDayIndex = i - 1;
        if (prevDayIndex >= 0 && selected[prevDayIndex]) {
          const prevRecipe = selected[prevDayIndex];
          if (prevRecipe.file.path === recipe.file.path) {
            return false;
          }
        }
        const nextDayIndex = i + 1;
        if (nextDayIndex < selected.length && selected[nextDayIndex]) {
          const nextRecipe = selected[nextDayIndex];
          if (nextRecipe.file.path === recipe.file.path) {
            return false;
          }
        }
        return true;
      });
      if (pool.length === 0) {
        pool = recipes.filter(
          (r) => meetsConstraints(r, day, settings.dayConstraints, false) && (!r.kidFriendly || r.familyFriendly)
        );
      }
      if (pool.length > 0) {
        const chosen = pool[Math.floor(Math.random() * pool.length)];
        selected[i] = chosen;
        assignedRecipes.add(chosen);
        if (chosen.familyFriendly)
          indicesWithFamilyMeals.add(i);
        else if (chosen.kidFriendly && !chosen.familyFriendly && kidMealIndices[i])
          indicesWithFamilyMeals.add(i);
      }
    }
  }
  const kidMeals = /* @__PURE__ */ new Map();
  const kidFriendlyRecipes = recipes.filter((r) => r.kidFriendly);
  for (let i = 0; i < count; i++) {
    const dayIndex = i % days.length;
    const day = days[dayIndex];
    if (!kidMealIndices[i])
      continue;
    if (indicesWithFamilyMeals.has(i) && settings.skipKidMealIfFamilyFriendly)
      continue;
    if (kidFriendlyRecipes.length === 0)
      break;
    const currentWeekKidMeals = [];
    const currentWeek = Math.floor(i / settings.mealsPerWeek);
    for (let j = currentWeek * settings.mealsPerWeek; j < (currentWeek + 1) * settings.mealsPerWeek; j++) {
      const meal = kidMeals.get(j);
      if (meal)
        currentWeekKidMeals.push(meal);
    }
    const kidMeal = KidMealStrategy(
      kidFriendlyRecipes,
      // The pool is filtered to kid-friendly only
      day,
      settings,
      [...selected.filter(Boolean), ...currentWeekKidMeals],
      true,
      // isKidMeal is true
      currentWeekKidMeals
      // Pass current week's kid meals separately for week constraint logic
    );
    if (kidMeal) {
      kidMeals.set(i, kidMeal);
    }
  }
  return { regularMeals: selected.filter(Boolean), kidMeals };
}
async function generateMealPlan(app, settings, getRecipesFunc, updateRecipeLastUsedFunc, filePathOverride) {
  const recipes = await getRecipesFunc();
  const count = settings.mealsPerWeek * settings.weeksToGenerate;
  const kidMealIndices = new Array(count).fill(false).map((_, i) => {
    var _a;
    const dayIndex = i % settings.daysOfWeek.length;
    const day = settings.daysOfWeek[dayIndex];
    return ((_a = settings.dayConstraints[day]) == null ? void 0 : _a.needsKidMeal) === true;
  });
  const { regularMeals, kidMeals } = selectRecipes(recipes, count, settings.daysOfWeek, kidMealIndices, settings);
  if (regularMeals.length < count) {
    new import_obsidian5.Notice(`Could only select ${regularMeals.length} out of ${count} meals. Check your constraints or add more recipes.`);
  }
  const date = new Date().toISOString().slice(0, 10);
  let folder = (0, import_obsidian5.normalizePath)((settings.mealPlanFolderPath || "Meals").trim());
  folder = folder.replace(/^\/+|\/+$/g, "");
  if (!folder)
    folder = "Meal Plans";
  folder = (0, import_obsidian5.normalizePath)(folder);
  const folderObj = app.vault.getAbstractFileByPath(folder);
  if (!folderObj) {
    await app.vault.createFolder(folder);
  }
  const filePath = (0, import_obsidian5.normalizePath)(filePathOverride || `${folder}/Meal Plan - ${date}.md`);
  let content = `---
`;
  content += `date_generated: ${date}
`;
  const tags = settings.mealPlanTags && settings.mealPlanTags.length > 0 ? settings.mealPlanTags : ["meal_plan"];
  content += `tags: [${tags.map((t) => t.trim()).filter(Boolean).join(", ")}]
`;
  content += `---
`;
  content += `# Weekly Meal Plan (${settings.weeksToGenerate} Weeks)

`;
  const allSelectedRecipes = /* @__PURE__ */ new Set([...regularMeals, ...Array.from(kidMeals.values())]);
  content += `## Meal Schedule
`;
  for (let w = 0; w < settings.weeksToGenerate; w++) {
    const week = w + 1;
    content += `
### \u{1F4C5} Week ${week}

`;
    regularMeals.slice(w * settings.mealsPerWeek, (w + 1) * settings.mealsPerWeek).forEach((recipe, index) => {
      const dayIndex = index % settings.daysOfWeek.length;
      const day = settings.daysOfWeek[dayIndex];
      const dayEmoji = getDayEmoji(day, settings);
      const absoluteIndex = w * settings.mealsPerWeek + index;
      content += `- [ ] **${dayEmoji} ${day}** - [[${recipe.file.basename}]]`;
      const kidMeal = kidMeals.get(absoluteIndex);
      if (kidMeal) {
        content += ` & [[${kidMeal.file.basename}]]`;
      }
      const totalTime = getRecipeTotalTime(recipe) + (kidMeal ? getRecipeTotalTime(kidMeal) : 0);
      const difficulty = recipe.difficulty || (kidMeal == null ? void 0 : kidMeal.difficulty) || "default";
      const difficultyEmoji = getDifficultyEmoji(difficulty, settings);
      content += ` - \u23F1\uFE0F ${totalTime} min - ${difficultyEmoji} ${difficulty.charAt(0).toUpperCase() + difficulty.slice(1)}`;
      content += `
`;
    });
  }
  if (settings.generateShoppingList) {
    content += "\n---\n";
    content += `# \u{1F6D2} Shopping List
`;
    for (let w = 0; w < settings.weeksToGenerate; w++) {
      const week = w + 1;
      content += `
## \u{1F4C5} Week ${week}
`;
      for (let d = 0; d < settings.mealsPerWeek; d++) {
        const absoluteIndex = w * settings.mealsPerWeek + d;
        const day = settings.daysOfWeek[d % settings.daysOfWeek.length];
        const dayEmoji = getDayEmoji(day, settings);
        content += `
### ${dayEmoji} ${day}
`;
        const recipe = regularMeals[absoluteIndex];
        if (recipe) {
          let label = `[[${recipe.file.basename}]]`;
          if (recipe.familyFriendly)
            label += " (Family Friendly)";
          else if (recipe.kidFriendly)
            label += " (Kid Friendly)";
          content += `
#### ${label}
`;
          recipe.ingredients.forEach((ingredient) => {
            content += `- [ ] ${ingredient}
`;
          });
        }
        const kidMeal = kidMeals.get(absoluteIndex);
        if (kidMeal) {
          let label = `[[${kidMeal.file.basename}]]`;
          if (kidMeal.familyFriendly)
            label += " (Family Friendly)";
          else if (kidMeal.kidFriendly)
            label += " (Kid Friendly)";
          content += `
#### ${label}
`;
          kidMeal.ingredients.forEach((ingredient) => {
            content += `- [ ] ${ingredient}
`;
          });
        }
      }
    }
    content += "\n";
  }
  const existingFile = app.vault.getAbstractFileByPath(filePath);
  let finalFile;
  if (existingFile instanceof import_obsidian5.TFile) {
    await app.vault.process(existingFile, (_data) => {
      return content;
    });
    finalFile = existingFile;
  } else {
    finalFile = await app.vault.create(filePath, content);
  }
  if (finalFile) {
    await app.workspace.getLeaf().openFile(finalFile);
  }
  for (const recipe of allSelectedRecipes) {
    await updateRecipeLastUsedFunc(recipe.file);
  }
  return filePath;
}
async function regenerateShoppingList(app, settings, filePath) {
  const file = app.vault.getAbstractFileByPath((0, import_obsidian5.normalizePath)(filePath));
  if (!(file instanceof import_obsidian5.TFile)) {
    new import_obsidian5.Notice("Meal plan file not found.");
    return;
  }
  let content = await app.vault.read(file);
  const recipes = await getRecipes(app, settings);
  const regularMeals = [];
  const kidMeals = /* @__PURE__ */ new Map();
  const mealLineRegex = /- \[ \] \*\*(.+?)\*\* - \[\[(.+?)\]\](?:\s*&\s*\[\[(.+?)\]\])?/g;
  let match;
  let mealIndex = 0;
  while ((match = mealLineRegex.exec(content)) !== null) {
    const mainRecipeName = match[2];
    const kidRecipeName = match[3];
    const mainRecipe = recipes.find((r) => r.file.basename === mainRecipeName);
    if (mainRecipe) {
      regularMeals[mealIndex] = mainRecipe;
    }
    if (kidRecipeName) {
      const kidRecipe = recipes.find((r) => r.file.basename === kidRecipeName);
      if (kidRecipe) {
        kidMeals.set(mealIndex, kidRecipe);
      }
    }
    mealIndex++;
  }
  const horizontalLinePattern = /\n---\n# 🛒 Shopping List/;
  const shoppingListMatch = content.match(horizontalLinePattern);
  if (shoppingListMatch) {
    const shoppingListStart = content.indexOf(shoppingListMatch[0]);
    content = content.substring(0, shoppingListStart);
  }
  if (settings.generateShoppingList && regularMeals.length > 0) {
    content += "\n---\n";
    content += `# \u{1F6D2} Shopping List
`;
    for (let w = 0; w < settings.weeksToGenerate; w++) {
      const week = w + 1;
      content += `
## \u{1F4C5} Week ${week}
`;
      for (let d = 0; d < settings.mealsPerWeek; d++) {
        const absoluteIndex = w * settings.mealsPerWeek + d;
        if (absoluteIndex >= regularMeals.length)
          break;
        const day = settings.daysOfWeek[d % settings.daysOfWeek.length];
        const dayEmoji = getDayEmoji(day, settings);
        content += `
### ${dayEmoji} ${day}
`;
        const recipe = regularMeals[absoluteIndex];
        if (recipe) {
          let label = `[[${recipe.file.basename}]]`;
          if (recipe.familyFriendly)
            label += " (Family Friendly)";
          else if (recipe.kidFriendly)
            label += " (Kid Friendly)";
          content += `
#### ${label}
`;
          recipe.ingredients.forEach((ingredient) => {
            content += `- [ ] ${ingredient}
`;
          });
        }
        const kidMeal = kidMeals.get(absoluteIndex);
        if (kidMeal) {
          content += `
#### [[${kidMeal.file.basename}]] (Kid's Meal)
`;
          kidMeal.ingredients.forEach((ingredient) => {
            content += `- [ ] ${ingredient}
`;
          });
        }
      }
    }
    content += "\n";
  }
  await app.vault.process(file, (_data) => {
    return content;
  });
}

// src/handlers/ActionHandlers.ts
var import_obsidian6 = require("obsidian");
async function changeMealForDay(app, settings, week, day, recipeName, updateRecipeLastUsed, originalChecklistLine, kidMealName) {
  if (!settings.currentMealPlanPath) {
    new import_obsidian6.Notice("No active meal plan found. Generate a meal plan first.");
    return;
  }
  const file = app.vault.getAbstractFileByPath(settings.currentMealPlanPath);
  if (!(file instanceof import_obsidian6.TFile)) {
    new import_obsidian6.Notice("Meal plan file not found.");
    return;
  }
  let content = await app.vault.read(file);
  const recipes = await getRecipes(app, settings);
  const newRecipe = recipes.find((r) => r.name === recipeName);
  if (!newRecipe) {
    new import_obsidian6.Notice(`Recipe '${recipeName}' not found.`);
    return;
  }
  const checklistLineMatch = originalChecklistLine.match(/^- \[.\] \*\*(.+?)\s([A-Za-z]+)\*\* - (.+)$/u);
  if (!checklistLineMatch) {
    new import_obsidian6.Notice("Could not parse the original checklist line.");
    return;
  }
  const dayEmoji = checklistLineMatch[1].trim();
  const targetDay = checklistLineMatch[2].trim();
  let checklistLine = `- [ ] **${dayEmoji} ${targetDay}** - [[${newRecipe.name}]]`;
  let newKidMeal;
  const dayConstraints = settings.dayConstraints[targetDay];
  if (kidMealName) {
    newKidMeal = recipes.find((r) => r.name === kidMealName);
    if (newKidMeal) {
      checklistLine += ` & [[${newKidMeal.name}]]`;
    }
  } else if ((dayConstraints == null ? void 0 : dayConstraints.needsKidMeal) && settings.skipKidMealIfFamilyFriendly !== true) {
    const kidFriendlyRecipes = recipes.filter((r) => r.kidFriendly);
    if (kidFriendlyRecipes.length > 0 && (!newRecipe.familyFriendly || !newRecipe.kidFriendly)) {
      newKidMeal = kidFriendlyRecipes[0];
      checklistLine += ` & [[${newKidMeal.name}]]`;
    }
  }
  const totalTime = getRecipeTotalTime(newRecipe) + (newKidMeal ? getRecipeTotalTime(newKidMeal) : 0);
  const difficulty = newRecipe.difficulty || (newKidMeal == null ? void 0 : newKidMeal.difficulty) || "default";
  const difficultyEmoji = getDifficultyEmoji(difficulty, settings);
  checklistLine += ` - \u23F1\uFE0F ${totalTime} min - ${difficultyEmoji} ${difficulty.charAt(0).toUpperCase() + difficulty.slice(1)}`;
  if (originalChecklistLine && content.includes(originalChecklistLine)) {
    content = content.replace(originalChecklistLine, checklistLine);
  } else {
    const weekSectionRegex = new RegExp(`### \\ud83d\\udcc5 Week ${week}\\n([\\s\\S]*?)(?=\\n### \\ud83d\\udcc5 Week|$)`, "i");
    const weekMatch = weekSectionRegex.exec(content);
    if (!weekMatch) {
      new import_obsidian6.Notice(`Week ${week} not found in the meal plan.`);
      return;
    }
    const weekSection = weekMatch[1];
    const checklistRegex = new RegExp(`(^- \\[.\\] \\*\\*${dayEmoji} ${targetDay}\\*\\* - ).*$`, "m");
    const newWeekSection = weekSection.replace(checklistRegex, checklistLine);
    content = content.replace(weekSection, newWeekSection);
  }
  await app.vault.process(file, (_data) => {
    return content;
  });
  await updateRecipeLastUsed(newRecipe.file);
  if (newKidMeal) {
    await updateRecipeLastUsed(newKidMeal.file);
  }
  if (settings.generateShoppingList) {
    await regenerateShoppingList(app, settings, settings.currentMealPlanPath);
  }
  new import_obsidian6.Notice(`Changed meal for Week ${week}, ${targetDay} to ${recipeName}.`);
}
async function swapMeals(app, settings, entry1, entry2) {
  if (!settings.currentMealPlanPath) {
    new import_obsidian6.Notice("No active meal plan found. Generate a meal plan first.");
    return;
  }
  const file = app.vault.getAbstractFileByPath((0, import_obsidian6.normalizePath)(settings.currentMealPlanPath));
  if (!(file instanceof import_obsidian6.TFile)) {
    new import_obsidian6.Notice("Meal plan file not found.");
    return;
  }
  const content = await app.vault.read(file);
  if (!content.includes(entry1.line) || !content.includes(entry2.line)) {
    new import_obsidian6.Notice("Could not find one or both selected meals in the meal plan.");
    return;
  }
  const checklistRegex = /^(- \[.\] \*\*.+?\*\* - )(.*)$/u;
  const match1 = entry1.line.match(checklistRegex);
  const match2 = entry2.line.match(checklistRegex);
  if (!match1 || !match2) {
    new import_obsidian6.Notice("Could not parse one or both checklist lines for swapping.");
    return;
  }
  const newLine1 = match1[1] + match2[2];
  const newLine2 = match2[1] + match1[2];
  let swappedContent = content.replace(entry1.line, "<<SWAP_PLACEHOLDER_1>>").replace(entry2.line, "<<SWAP_PLACEHOLDER_2>>");
  swappedContent = swappedContent.replace("<<SWAP_PLACEHOLDER_1>>", newLine1).replace("<<SWAP_PLACEHOLDER_2>>", newLine2);
  await app.vault.process(file, (_data) => {
    return swappedContent;
  });
  if (settings.generateShoppingList) {
    await regenerateShoppingList(app, settings, settings.currentMealPlanPath);
  }
  new import_obsidian6.Notice(`Swapped meals between '${entry1.day} (Week ${entry1.week})' and '${entry2.day} (Week ${entry2.week})'!`);
}

// src/main.ts
var WeeklyMealPlannerPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("chef-hat", "Weekly meal planner", (evt) => {
      const menu = new import_obsidian7.Menu();
      menu.addItem(
        (item) => item.setTitle("Generate meal plan").setIcon("chef-hat").onClick(async () => {
          await this.generateMealPlan();
        })
      );
      menu.addItem(
        (item) => item.setTitle("Swap meals between days").setIcon("switch").onClick(() => {
          new SwapMealsModal(this.app, this, (entry1, entry2) => {
            void swapMeals(this.app, this.settings, entry1, entry2);
          }).open();
        })
      );
      menu.addItem(
        (item) => item.setTitle("Change meal for a day").setIcon("edit").onClick(() => {
          new ChangeMealModal(
            this.app,
            this,
            (week, day, recipeName, originalChecklistLine, kidMealName) => {
              void changeMealForDay(
                this.app,
                this.settings,
                week,
                day,
                recipeName,
                this.updateRecipeLastUsed.bind(this),
                originalChecklistLine,
                kidMealName
              );
            }
          ).open();
        })
      );
      menu.addItem(
        (item) => item.setTitle("Create new recipe note").setIcon("file-plus").onClick(async () => {
          await this.createRecipeNote();
        })
      );
      menu.showAtMouseEvent(evt);
    });
    this.addCommand({
      id: "generate-meal-plan",
      name: "Generate meal plan",
      callback: async () => {
        await this.generateMealPlan();
      }
    });
    this.addCommand({
      id: "swap-meals",
      name: "Swap meals between days",
      callback: () => {
        new SwapMealsModal(this.app, this, (entry1, entry2) => {
          void swapMeals(this.app, this.settings, entry1, entry2);
        }).open();
      }
    });
    this.addCommand({
      id: "change-meal",
      name: "Change meal for a day",
      callback: () => {
        new ChangeMealModal(
          this.app,
          this,
          (week, day, recipeName, originalChecklistLine, kidMealName) => {
            void changeMealForDay(
              this.app,
              this.settings,
              week,
              day,
              recipeName,
              this.updateRecipeLastUsed.bind(this),
              originalChecklistLine,
              kidMealName
            );
          }
        ).open();
      }
    });
    this.addCommand({
      id: "create-recipe-template",
      name: "Create new recipe note",
      callback: async () => {
        await this.createRecipeNote();
      }
    });
    this.addSettingTab(new MealPlannerSettingTab(this.app, this));
  }
  // Helper function to bind getRecipes for external use
  getRecipesBound() {
    return getRecipes(this.app, this.settings);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  // Calls the core generator and updates settings
  async generateMealPlan() {
    const app = this.app;
    const settings = this.settings;
    const getRecipesBound = this.getRecipesBound.bind(this);
    const updateRecipeLastUsed = this.updateRecipeLastUsed.bind(this);
    const date = new Date().toISOString().slice(0, 10);
    let folder = (settings.mealPlanFolderPath || "Meals").trim();
    folder = (0, import_obsidian7.normalizePath)(folder);
    if (!folder)
      folder = "Meals";
    const filePath = (0, import_obsidian7.normalizePath)(`${folder}/Meal Plan - ${date}.md`);
    const existingFile = app.vault.getAbstractFileByPath(filePath);
    if (existingFile) {
      new OverwriteOrNewFileModal(
        app,
        filePath,
        async () => {
          const generatedPath = await generateMealPlan(app, settings, getRecipesBound, updateRecipeLastUsed);
          if (generatedPath) {
            this.settings.currentMealPlanPath = generatedPath;
            await this.saveSettings();
          }
        },
        async () => {
          const now = new Date();
          const postfix = `_${now.getHours()}-${now.getMinutes()}-${now.getSeconds()}`;
          const uniqueFilePath = (0, import_obsidian7.normalizePath)(`${folder}/Meal Plan - ${date}${postfix}.md`);
          const origFolder = settings.mealPlanFolderPath;
          settings.mealPlanFolderPath = folder;
          const generatedPath = await generateMealPlan(app, settings, getRecipesBound, updateRecipeLastUsed, uniqueFilePath);
          settings.mealPlanFolderPath = origFolder;
          if (generatedPath) {
            this.settings.currentMealPlanPath = generatedPath;
            await this.saveSettings();
          }
        }
      ).open();
    } else {
      const generatedPath = await generateMealPlan(app, settings, getRecipesBound, updateRecipeLastUsed);
      if (generatedPath) {
        this.settings.currentMealPlanPath = generatedPath;
        await this.saveSettings();
      }
    }
  }
  async createRecipeNote() {
    const recipeName = await this.promptForRecipeName();
    if (!recipeName)
      return;
    const recipeFolder = this.settings.recipeFolderPath || "Recipes";
    const recipePath = (0, import_obsidian7.normalizePath)(`${recipeFolder}/${recipeName}.md`);
    const existingFile = this.app.vault.getAbstractFileByPath(recipePath);
    if (existingFile) {
      new import_obsidian7.Notice(`Recipe "${recipeName}" already exists!`);
      return;
    }
    const folder = this.app.vault.getAbstractFileByPath(recipeFolder);
    if (!folder) {
      await this.app.vault.createFolder(recipeFolder);
    }
    const template = this.generateRecipeTemplate(recipeName);
    try {
      const file = await this.app.vault.create(recipePath, template);
      const leaf = this.app.workspace.getLeaf();
      await leaf.openFile(file);
      new import_obsidian7.Notice(`Recipe "${recipeName}" created successfully!`);
    } catch (error) {
      new import_obsidian7.Notice(`Failed to create recipe: ${error.message}`);
    }
  }
  async promptForRecipeName() {
    return new Promise((resolve) => {
      const modal = new RecipeNameModal(this.app, (recipeName) => {
        resolve(recipeName || null);
      });
      modal.open();
    });
  }
  generateRecipeTemplate(recipeName) {
    return `---
tags:
  - recipe
meal_type: 
prep_time: 
cook_time: 
difficulty: easy
family_friendly: false
kid_friendly: false
season: []
rating: 
lastUsed: 
---
# ${recipeName}

## \u23F1\uFE0F Quick Info
- \u{1F52A} **Prep Time:** x minutes
- \u{1F525} **Cook Time:** x minutes
- \u{1F468}\u200D\u{1F373} **Difficulty:** Easy/Medium/Hard
- \u{1F37D}\uFE0F **Meal Type:** 
- \u{1F468}\u200D\u{1F469}\u200D\u{1F467}\u200D\u{1F466} **Family Friendly:** Yes/No
- \u{1F476} **Kid Friendly:** Yes/No

## \u{1F6D2} Ingredients
- 
- 
- 

## \u{1F469}\u200D\u{1F373} Instructions
1. 
2. 
3. 

## \u{1F4DD} Notes
-
-
-

## \u{1F4A1} Tips
- 
-
- 

`;
  }
  async updateRecipeLastUsed(file) {
    const timestamp = Date.now();
    await this.app.fileManager.processFrontMatter(file, (frontmatter) => {
      frontmatter.lastUsed = timestamp;
    });
  }
};
