/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BetterFilePropertiesViewPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  coverPropertyName: "cover",
  hideMetadataContainer: true,
  showThumbnail: true
};
var BetterFilePropertiesViewSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Show Thumbnail").setDesc("Display thumbnail images from the frontmatter property").addToggle((value) => value.setValue(this.plugin.settings.showThumbnail).onChange((value2) => __async(this, null, function* () {
      this.plugin.settings.showThumbnail = value2;
      yield this.plugin.saveSettings();
      this.plugin.updateFilePropertiesView();
      this.display();
    })));
    if (this.plugin.settings.showThumbnail) {
      new import_obsidian.Setting(containerEl).setName("Thumbnail Property Name").setDesc("The frontmatter property name to look for and display as an image").addText((text) => text.setPlaceholder("cover").setValue(this.plugin.settings.coverPropertyName).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.coverPropertyName = value || "cover";
        yield this.plugin.saveSettings();
        this.plugin.updateFilePropertiesView();
      })));
    }
    new import_obsidian.Setting(containerEl).setName("Hide metadata container").setDesc("Hides the metadata container if Properties View is active").addToggle((value) => value.setValue(this.plugin.settings.hideMetadataContainer).onChange((value2) => __async(this, null, function* () {
      this.plugin.settings.hideMetadataContainer = value2;
      yield this.plugin.saveSettings();
      this.plugin.updateMetadataContainer();
    })));
  }
};

// main.ts
var BetterFilePropertiesViewPlugin = class extends import_obsidian2.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addSettingTab(new BetterFilePropertiesViewSettingTab(this.app, this));
      this.registerEvent(
        this.app.workspace.on("active-leaf-change", () => {
          this.updateFilePropertiesView();
          this.updateMetadataContainer();
        })
      );
      this.registerEvent(
        this.app.metadataCache.on("changed", () => {
          this.updateFilePropertiesView();
          this.updateMetadataContainer();
        })
      );
      this.updateFilePropertiesView();
      this.updateMetadataContainer();
    });
  }
  onunload() {
    this.resetMetadataContainer();
    this.removePropertyImage();
  }
  updateFilePropertiesView() {
    this.removePropertyImage();
    const activeLeaf = this.app.workspace.activeLeaf;
    if (!activeLeaf) return;
    const file = this.app.workspace.getActiveFile();
    if (!file || !(file instanceof import_obsidian2.TFile)) return;
    const metadata = this.app.metadataCache.getFileCache(file);
    if (!metadata || !metadata.frontmatter) return;
    const converPropertyName = this.settings.coverPropertyName;
    const cover = metadata.frontmatter[converPropertyName];
    if (!cover) return;
    const container = document.querySelector(
      'div.workspace-leaf-content[data-type="file-properties"] div.view-content'
    );
    if (!container) return;
    const imageContainer = document.createElement("div");
    imageContainer.className = "better-file-properties-image-container";
    const image = document.createElement("img");
    image.className = "better-file-properties-image";
    image.src = cover;
    image.onerror = () => {
      imageContainer.remove();
    };
    imageContainer.appendChild(image);
    container.prepend(imageContainer);
  }
  updateMetadataContainer() {
    this.resetMetadataContainer();
    if (this.settings.hideMetadataContainer && this.isFilePropertiesViewActive()) {
      document.body.addClass("hide-metadata-container");
    }
  }
  isFilePropertiesViewActive() {
    const el = document.querySelector('div.workspace-tab-header[data-type="file-properties"]');
    return el == null ? void 0 : el.hasClass("is-active");
  }
  resetMetadataContainer() {
    document.body.removeClass("hide-metadata-container");
  }
  removePropertyImage() {
    const imageContainer = document.querySelector(
      'div.workspace-leaf-content[data-type="file-properties"] div.view-content .better-file-properties-image-container'
    );
    if (imageContainer) {
      imageContainer.remove();
    }
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
};
